import { sql } from "drizzle-orm";
import { bigserial, boolean, check, foreignKey, index, integer, jsonb, pgSchema, primaryKey, text, timestamp, uniqueIndex, uuid, type AnyPgColumn } from "drizzle-orm/pg-core";
import type { Candidate, DecisionRecord } from "../types.js";

export const fieldGuideSchema = pgSchema("field_guide");

function verdictDecisionId(): AnyPgColumn { return verdictEvents.decisionId; }
export const candidates = fieldGuideSchema.table("candidates", { candidateId: uuid("candidate_id").primaryKey(), idempotencyKey: text("idempotency_key").notNull().unique("candidates_idempotency_key_key"), payload: jsonb("payload").$type<Candidate>().notNull(), payloadHash: text("payload_hash").notNull(), createdAt: timestamp("created_at", { withTimezone:true }).notNull() });
export const reviewRounds = fieldGuideSchema.table("review_rounds", { candidateId:uuid("candidate_id").notNull(), round:integer("round").notNull(), kind:text("kind").notNull(), dueAt:timestamp("due_at",{withTimezone:true}), verdictId:uuid("verdict_id").unique("review_rounds_verdict_id_key") }, table => [primaryKey({name:"review_rounds_pkey",columns:[table.candidateId,table.round]}), foreignKey({name:"review_rounds_candidate_id_fkey",columns:[table.candidateId],foreignColumns:[candidates.candidateId]}), foreignKey({name:"review_rounds_verdict_id_fkey",columns:[table.verdictId],foreignColumns:[verdictDecisionId()]}), check("review_rounds_kind_check",sql`${table.kind} in ('initial', 'scheduled')`)]);
export const verdictEvents = fieldGuideSchema.table("verdict_events", { sequence:bigserial("sequence",{mode:"bigint"}).primaryKey(), decisionId:uuid("decision_id").notNull().unique("verdict_events_decision_id_key"), candidateId:uuid("candidate_id").notNull(), round:integer("round").notNull(), action:text("action").notNull(), reviewer:text("reviewer").notNull(), reviewedAt:timestamp("reviewed_at",{withTimezone:true}).notNull(), nextReviewAt:timestamp("next_review_at",{withTimezone:true}), roundKind:text("round_kind").notNull(), effect:text("effect").notNull(), amendsDecisionId:uuid("amends_decision_id") }, table => [foreignKey({name:"verdict_events_candidate_id_round_fkey",columns:[table.candidateId,table.round],foreignColumns:[reviewRounds.candidateId,reviewRounds.round]}), foreignKey({name:"verdict_events_amends_decision_id_fkey",columns:[table.amendsDecisionId],foreignColumns:[table.decisionId]}), check("verdict_events_round_kind_check",sql`${table.roundKind} in ('initial', 'scheduled')`), check("verdict_events_effect_check",sql`${table.effect} in ('activate', 'deactivate')`), uniqueIndex("verdict_events_one_amendment_per_parent").on(table.amendsDecisionId).where(sql`${table.amendsDecisionId} is not null`)]);
export const applicationReceipts = fieldGuideSchema.table("application_receipts", { idempotencyKey:text("idempotency_key").primaryKey(), payloadHash:text("payload_hash").notNull(), decisionId:uuid("decision_id").notNull(), appliedAt:timestamp("applied_at",{withTimezone:true}).notNull(), result:text("result").notNull() }, table => [foreignKey({name:"application_receipts_decision_id_fkey",columns:[table.decisionId],foreignColumns:[verdictEvents.decisionId]}),check("application_receipts_result_check",sql`${table.result} in ('applied', 'already_applied')`)]);
export const fieldGuideSchemaMigrations = fieldGuideSchema.table("field_guide_schema_migrations", {
  name: text("name").primaryKey(),
  checksum: text("checksum").notNull(),
  appliedAt: timestamp("applied_at", { withTimezone: true }).notNull(),
  adopted: boolean("adopted").notNull(),
});
export const decisionRecords = fieldGuideSchema.table("decision_records", { sequence:bigserial("sequence",{mode:"bigint"}).primaryKey(), decisionRecordId:uuid("decision_record_id").notNull().unique("decision_records_record_id_key"), idempotencyKey:text("idempotency_key").notNull().unique("decision_records_idempotency_key_key"), payload:jsonb("payload").$type<DecisionRecord>().notNull(), payloadHash:text("payload_hash").notNull(), createdAt:timestamp("created_at",{withTimezone:true}).notNull(), receivedAt:timestamp("received_at",{withTimezone:true}).notNull() });
export const decisionFeedbackEvents = fieldGuideSchema.table("decision_feedback_events", { sequence:bigserial("sequence",{mode:"bigint"}).primaryKey(), feedbackId:uuid("feedback_id").notNull().unique("decision_feedback_events_feedback_id_key"), decisionRecordId:uuid("decision_record_id").notNull(), action:text("action").notNull(), comment:text("comment"), reviewer:text("reviewer").notNull(), reviewedAt:timestamp("reviewed_at",{withTimezone:true}).notNull(), amendsFeedbackId:uuid("amends_feedback_id").unique("decision_feedback_events_amends_key") }, table => [foreignKey({name:"decision_feedback_events_record_fkey",columns:[table.decisionRecordId],foreignColumns:[decisionRecords.decisionRecordId]}),foreignKey({name:"decision_feedback_events_amends_fkey",columns:[table.amendsFeedbackId],foreignColumns:[table.feedbackId]}),check("decision_feedback_events_action_check",sql`${table.action} in ('up', 'down', 'dismiss')`),index("decision_feedback_events_record_sequence_idx").on(table.decisionRecordId,sql`${table.sequence} desc`)]);
export const decisionPromotions = fieldGuideSchema.table("decision_promotions", { candidateId:uuid("candidate_id").primaryKey(), idempotencyKey:text("idempotency_key").notNull().unique("decision_promotions_idempotency_key_key"), payloadHash:text("payload_hash").notNull(), promotedAt:timestamp("promoted_at",{withTimezone:true}).notNull(), promotedBy:text("promoted_by").notNull() }, table => [foreignKey({name:"decision_promotions_candidate_fkey",columns:[table.candidateId],foreignColumns:[candidates.candidateId]})]);
export const decisionPromotionRecords = fieldGuideSchema.table("decision_promotion_records", { candidateId:uuid("candidate_id").notNull(), decisionRecordId:uuid("decision_record_id").notNull().unique("decision_promotion_records_record_key"), ordinal:integer("ordinal").notNull() }, table => [primaryKey({name:"decision_promotion_records_pkey",columns:[table.candidateId,table.decisionRecordId]}),foreignKey({name:"decision_promotion_records_candidate_fkey",columns:[table.candidateId],foreignColumns:[decisionPromotions.candidateId]}),foreignKey({name:"decision_promotion_records_record_fkey",columns:[table.decisionRecordId],foreignColumns:[decisionRecords.decisionRecordId]})]);
