import { describe, expect, it, vi } from "vitest";
import { startServer } from "../src/server.js";
import { MemoryReviewRepository } from "../src/memory-repository.js";
import type { Config } from "../src/config.js";
const config:Config={backend:"sqlite",sqlitePath:"/tmp/not-used.sqlite",importOnStart:false,importAllowOverwrite:false,port:3000,agentApiToken:"token",publicBaseUrl:"https://review.example"};
describe("startup readiness",()=>{
  it("does not bind before repository initialization",async()=>{let release:()=>void=()=>undefined;const ready=new Promise<void>(resolve=>{release=resolve;});const serve=vi.fn(()=>({stop:vi.fn()}));const pending=startServer({config,createRepository:async()=>{await ready;const repository=new MemoryReviewRepository();return {repository,checkpoint:vi.fn(),close:()=>repository.close()};},serve});expect(serve).not.toHaveBeenCalled();release();const running=await pending;expect(serve).toHaveBeenCalledOnce();await running.shutdown();});
  it("never binds when initialization fails",async()=>{const serve=vi.fn(()=>({stop:vi.fn()}));await expect(startServer({config,createRepository:async()=>{throw new Error("migration failed");},serve})).rejects.toThrow("migration failed");expect(serve).not.toHaveBeenCalled();});
  it("logs only the safe startup import report",async()=>{const repository=new MemoryReviewRepository();const log=vi.fn();const report={schema:1 as const,tables:{candidates:{count:1,hash:"a"},review_rounds:{count:1,hash:"b"},verdict_events:{count:1,hash:"c"},application_receipts:{count:0,hash:"d"},field_guide_schema_migrations:{count:1,hash:"e"}},maxSequence:"7",sequence:{lastValue:"9",isCalled:true,nextValue:"10"}};const running=await startServer({config:{...config,databaseUrl:"postgres://user:secret@db/private",importOnStart:true},createRepository:async()=>({repository,checkpoint:vi.fn(),close:()=>repository.close(),startupReport:report}),serve:()=>({stop:vi.fn()}),log});const parsed=JSON.parse(String(log.mock.calls[0]?.[0])) as Record<string,unknown>;expect(parsed).toEqual({event:"postgres_import",...report});expect(JSON.stringify(parsed)).not.toContain("secret");expect(JSON.stringify(parsed)).not.toContain("private");expect(JSON.stringify(parsed)).not.toContain("payload");await running.shutdown();});
});
