import type { MutationCtx } from "./_generated/server";
import { ConvexError } from "convex/values";
import { LEGACY_TOKEN_PATTERN } from "./constants";

export async function createServerCapability(
  ctx: Pick<MutationCtx, "db">,
  claimedAt: number,
): Promise<string> {
  // Convex IDs are generated by the database and are never reused. Keeping the
  // claim forever also makes the non-reuse invariant explicit after content is
  // deleted.
  return await ctx.db.insert("capabilityClaims", { claimedAt });
}

export async function claimLegacyCapability(
  ctx: Pick<MutationCtx, "db">,
  token: string,
  claimedAt: number,
): Promise<void> {
  if (!LEGACY_TOKEN_PATTERN.test(token)) {
    throw new ConvexError({
      code: "INVALID_TOKEN",
      message: "The legacy document link token is invalid.",
    });
  }
  const existing = await ctx.db
    .query("capabilityClaims")
    .withIndex("by_token", (query) => query.eq("token", token))
    .unique();
  if (existing) {
    throw new ConvexError({
      code: "TOKEN_ALREADY_USED",
      message: "This document capability has already been used.",
    });
  }
  await ctx.db.insert("capabilityClaims", { token, claimedAt });
}

export async function ensureCapabilityClaim(
  ctx: Pick<MutationCtx, "db">,
  token: string,
  claimedAt: number,
): Promise<void> {
  const claimId = ctx.db.normalizeId("capabilityClaims", token);
  if (claimId && (await ctx.db.get("capabilityClaims", claimId))) {
    return;
  }
  const existing = await ctx.db
    .query("capabilityClaims")
    .withIndex("by_token", (query) => query.eq("token", token))
    .unique();
  if (!existing) {
    await ctx.db.insert("capabilityClaims", { token, claimedAt });
  }
}
