import { sql } from "drizzle-orm";
import { bigserial, boolean, check, foreignKey, integer, jsonb, pgTable, primaryKey, text, timestamp, uniqueIndex, uuid, type AnyPgColumn } from "drizzle-orm/pg-core";
import type { Candidate } from "../types.js";

function verdictDecisionId(): AnyPgColumn { return verdictEvents.decisionId; }
export const candidates = pgTable("candidates", { candidateId: uuid("candidate_id").primaryKey(), idempotencyKey: text("idempotency_key").notNull().unique("candidates_idempotency_key_key"), payload: jsonb("payload").$type<Candidate>().notNull(), payloadHash: text("payload_hash").notNull(), createdAt: timestamp("created_at", { withTimezone:true }).notNull() });
export const reviewRounds = pgTable("review_rounds", { candidateId:uuid("candidate_id").notNull(), round:integer("round").notNull(), kind:text("kind").notNull(), dueAt:timestamp("due_at",{withTimezone:true}), verdictId:uuid("verdict_id").unique("review_rounds_verdict_id_key") }, table => [primaryKey({name:"review_rounds_pkey",columns:[table.candidateId,table.round]}), foreignKey({name:"review_rounds_candidate_id_fkey",columns:[table.candidateId],foreignColumns:[candidates.candidateId]}), foreignKey({name:"review_rounds_verdict_id_fkey",columns:[table.verdictId],foreignColumns:[verdictDecisionId()]}), check("review_rounds_kind_check",sql`${table.kind} in ('initial', 'scheduled')`)]);
export const verdictEvents = pgTable("verdict_events", { sequence:bigserial("sequence",{mode:"bigint"}).primaryKey(), decisionId:uuid("decision_id").notNull().unique("verdict_events_decision_id_key"), candidateId:uuid("candidate_id").notNull(), round:integer("round").notNull(), action:text("action").notNull(), reviewer:text("reviewer").notNull(), reviewedAt:timestamp("reviewed_at",{withTimezone:true}).notNull(), nextReviewAt:timestamp("next_review_at",{withTimezone:true}), roundKind:text("round_kind").notNull(), effect:text("effect").notNull(), amendsDecisionId:uuid("amends_decision_id") }, table => [foreignKey({name:"verdict_events_candidate_id_round_fkey",columns:[table.candidateId,table.round],foreignColumns:[reviewRounds.candidateId,reviewRounds.round]}), foreignKey({name:"verdict_events_amends_decision_id_fkey",columns:[table.amendsDecisionId],foreignColumns:[table.decisionId]}), check("verdict_events_round_kind_check",sql`${table.roundKind} in ('initial', 'scheduled')`), check("verdict_events_effect_check",sql`${table.effect} in ('activate', 'deactivate')`), uniqueIndex("verdict_events_one_amendment_per_parent").on(table.amendsDecisionId).where(sql`${table.amendsDecisionId} is not null`)]);
export const applicationReceipts = pgTable("application_receipts", { idempotencyKey:text("idempotency_key").primaryKey(), payloadHash:text("payload_hash").notNull(), decisionId:uuid("decision_id").notNull(), appliedAt:timestamp("applied_at",{withTimezone:true}).notNull(), result:text("result").notNull() }, table => [foreignKey({name:"application_receipts_decision_id_fkey",columns:[table.decisionId],foreignColumns:[verdictEvents.decisionId]}),check("application_receipts_result_check",sql`${table.result} in ('applied', 'already_applied')`)]);
export const fieldGuideSchemaMigrations = pgTable("field_guide_schema_migrations", { name:text("name").primaryKey(), checksum:text("checksum").notNull(), appliedAt:timestamp("applied_at",{withTimezone:true}).notNull(), adopted:boolean("adopted").notNull() });
