import crypto from "node:crypto";
import { addDays, ConflictError, type Candidate, type Decision, type QueueItem, type ReviewRepository, type Scope, type Summary, type VerdictInput } from "./types.js";
type State = { candidate: Candidate; round: number; kind: "initial" | "scheduled"; dueAt?: string; closed: boolean };
export class MemoryReviewRepository implements ReviewRepository {
  private candidates = new Map<string, { key: string; json: string; state: State }>(); private keys = new Map<string,string>(); private events: Decision[] = []; private receipts = new Map<string,string>();
  async createCandidate(key:string,candidate:Candidate){const json=JSON.stringify(candidate);const old=this.keys.get(key);if(old){if(old!==json)throw new ConflictError("Idempotency key already has different content.");return "replay" as const;}if(this.candidates.has(candidate.candidateId))throw new ConflictError("Candidate already exists.");this.keys.set(key,json);this.candidates.set(candidate.candidateId,{key,json,state:{candidate,round:1,kind:"initial",closed:false}});return "created" as const;}
  async createReceipt(key:string,decisionId:string,appliedAt:string,result:"applied"|"already_applied"){if(!this.events.some(e=>e.decisionId===decisionId))throw new Error("Decision not found.");const json=JSON.stringify({decisionId,appliedAt,result});const old=this.receipts.get(key);if(old){if(old!==json)throw new ConflictError("Idempotency key already has different content.");return "replay" as const;}this.receipts.set(key,json);return "created" as const;}
  async decisions(cursor:string|undefined,limit:number){let offset=0;if(cursor){try{offset=Number(Buffer.from(cursor,"base64url").toString("utf8"));}catch{throw new Error("Invalid cursor.");}if(!Number.isInteger(offset)||offset<0)throw new Error("Invalid cursor.");}const decisions=this.events.slice(offset,offset+limit);const next=offset+decisions.length;return {decisions,...(next<this.events.length?{nextCursor:Buffer.from(String(next)).toString("base64url")}: {})};}
  async queue(scope:Scope|undefined,now:Date){return [...this.candidates.values()].map(v=>v.state).filter(s=>!s.closed&&(!scope||s.candidate.scope===scope)).map(s=>toItem(s,now));}
  async decide(id:string,round:number,input:VerdictInput,now:Date){const record=this.candidates.get(id);if(!record)throw new Error("Candidate not found.");const state=record.state;if(state.closed||state.round!==round)throw new ConflictError("Review round is already decided.");const allowed=state.kind==="initial"?["approve","reject","defer"]:["confirm_valid","mark_invalid","defer"];if(!allowed.includes(input.action))throw new Error("Action is not valid for this review round.");let nextReviewAt:string|undefined;if(input.action==="defer"){if(!input.deferUntil)throw new Error("deferUntil is required.");const d=new Date(input.deferUntil);if(!Number.isFinite(d.getTime())||d<=now||d>addDays(now,90))throw new Error("deferUntil must be within the next 90 days.");nextReviewAt=d.toISOString();state.round++;state.dueAt=nextReviewAt;}else if(input.action==="approve"){nextReviewAt=addDays(now,7).toISOString();state.kind="scheduled";state.round++;state.dueAt=nextReviewAt;}else if(input.action==="confirm_valid"){nextReviewAt=addDays(now,round===2?30:90).toISOString();state.round++;state.dueAt=nextReviewAt;}else state.closed=true;const c=state.candidate;const decision:Decision={decisionId:crypto.randomUUID(),candidateId:id,round,action:input.action,scope:c.scope,lessonKey:c.lessonKey,title:c.title,body:c.body,reviewedAt:now.toISOString(),...(nextReviewAt?{nextReviewAt}:{})};this.events.push(decision);return decision;}
  async summary(now:Date){const q=await this.queue(undefined,now);return {pending:q.filter(x=>x.status==="pending").length,due:q.filter(x=>x.status==="due").length,overdue:q.filter(x=>x.status==="overdue").length};}
  async migrate(){} async close(){}
}
function toItem(s:State,now:Date):QueueItem{let status:QueueItem["status"]="pending";if(s.dueAt){const due=new Date(s.dueAt);status=due<now?"overdue":"due";}return {candidate:s.candidate,round:s.round,kind:s.kind,...(s.dueAt?{dueAt:s.dueAt}:{}),status};}
