// @vitest-environment jsdom
import "@testing-library/jest-dom/vitest";
import { cleanup,fireEvent,render,screen,waitFor } from "@testing-library/react";
import { afterEach,describe,expect,it,vi } from "vitest";
import { App } from "../src/client/App";

afterEach(()=>{cleanup();vi.unstubAllGlobals();globalThis.history.replaceState(null,"","/");});
describe("dashboard",()=>{
  it("shows empty, capacity, Discord state, and accessible add dialog",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>Response.json({monitors:[],capacity:{used:0,limit:40},discordConfigured:false})));render(<App/>);expect(await screen.findByText("No monitors yet")).toBeInTheDocument();expect(screen.getByText("0/40")).toBeInTheDocument();expect(screen.getByText(/Discord notifications are not configured/)).toBeInTheDocument();fireEvent.click(screen.getAllByRole("button",{name:"Add monitor"})[0]);expect(screen.getByRole("dialog",{name:"Add monitor"})).toBeInTheDocument();expect(screen.getByLabelText("Name")).toHaveFocus();});
  it("shows text status, offers editing, and asks before deletion",async()=>{const monitor={id:1,name:"Example",url:"https://example.com/",hostname:"example.com",enabled:true,status:"down",latestLatencyMs:120,latestStatusCode:500,lastCheckedAt:"2026-01-01T00:00:00Z",uptime24h:99,uptime30d:99.5,scheduleSlot:0};const fetcher=vi.fn(async(input:RequestInfo|URL)=>String(input).includes("history")?Response.json({uptime:99,checks:[],nextCursor:null,incidents:[],buckets:[]}):Response.json({monitors:[monitor],capacity:{used:1,limit:40},discordConfigured:true}));vi.stubGlobal("fetch",fetcher);vi.stubGlobal("confirm",vi.fn(()=>false));render(<App/>);fireEvent.click(await screen.findByRole("button",{name:/Open Example, status down/}));expect(await screen.findByRole("dialog",{name:"Example"})).toBeInTheDocument();fireEvent.click(screen.getByRole("button",{name:"Edit"}));expect(screen.getByRole("dialog",{name:"Edit monitor"})).toBeInTheDocument();expect(document.querySelectorAll('[aria-modal="true"]')).toHaveLength(1);expect(screen.getByLabelText("Name")).toHaveValue("Example");expect(screen.getByLabelText("Name")).toHaveFocus();fireEvent.click(screen.getByRole("button",{name:"Cancel"}));fireEvent.click(screen.getByRole("button",{name:"Delete"}));expect(globalThis.confirm).toHaveBeenCalled();await waitFor(()=>expect(fetcher).not.toHaveBeenCalledWith(expect.stringContaining("/api/monitors/1"),expect.objectContaining({method:"DELETE"})));});
  it("keeps add input and dialog open when creation fails",async()=>{const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>init?.method==="POST"?Response.json({error:{code:"duplicate_url",message:"That URL is already monitored"}},{status:409}):Response.json({monitors:[],capacity:{used:0,limit:40},discordConfigured:false}));vi.stubGlobal("fetch",fetcher);render(<App/>);fireEvent.click((await screen.findAllByRole("button",{name:"Add monitor"}))[0]);fireEvent.change(screen.getByLabelText("Name"),{target:{value:"Existing"}});fireEvent.change(screen.getByLabelText("Website URL"),{target:{value:"https://example.com"}});fireEvent.click(screen.getByRole("button",{name:"Add and check"}));expect(await screen.findByText("That URL is already monitored")).toBeInTheDocument();expect(screen.getByRole("dialog",{name:"Add monitor"})).toBeInTheDocument();expect(screen.getByLabelText("Name")).toHaveValue("Existing");});
  it("keeps edit and detail context when mutations fail",async()=>{const monitor={id:1,name:"Example",url:"https://example.com/",hostname:"example.com",enabled:true,status:"up" as const,latestLatencyMs:20,latestStatusCode:200,lastCheckedAt:"2026-01-01T00:00:00Z",uptime24h:100,uptime30d:100,scheduleSlot:0};const fetcher=vi.fn(async(input:RequestInfo|URL,init?:RequestInit)=>{if(init?.method==="PATCH")return Response.json({error:{code:"duplicate_url",message:"That URL is already monitored"}},{status:409});if(init?.method==="DELETE")return Response.json({error:{code:"internal_error",message:"Delete failed"}},{status:500});return String(input).includes("history")?Response.json({uptime:100,checks:[],nextCursor:null,incidents:[],buckets:[]}):Response.json({monitors:[monitor],capacity:{used:1,limit:40},discordConfigured:false});});vi.stubGlobal("fetch",fetcher);vi.stubGlobal("confirm",vi.fn(()=>true));render(<App/>);fireEvent.click(await screen.findByRole("button",{name:/Open Example/}));fireEvent.click(await screen.findByRole("button",{name:"Edit"}));fireEvent.change(screen.getByLabelText("Website URL"),{target:{value:"https://duplicate.example"}});fireEvent.click(screen.getByRole("button",{name:"Save changes"}));expect(await screen.findByText("That URL is already monitored")).toBeInTheDocument();expect(screen.getByRole("dialog",{name:"Edit monitor"})).toBeInTheDocument();expect(screen.getByLabelText("Website URL")).toHaveValue("https://duplicate.example");fireEvent.click(screen.getByRole("button",{name:"Cancel"}));fireEvent.click(screen.getByRole("button",{name:"Delete"}));expect(await screen.findByText("Delete failed")).toBeInTheDocument();expect(screen.getByRole("dialog",{name:"Example"})).toBeInTheDocument();});
  it("opens and clears monitor deep links",async()=>{globalThis.history.replaceState(null,"","/?monitor=1");const monitor={id:1,name:"Linked",url:"https://linked.example/",hostname:"linked.example",enabled:true,status:"up" as const,latestLatencyMs:20,latestStatusCode:200,lastCheckedAt:null,uptime24h:null,uptime30d:null,scheduleSlot:0};vi.stubGlobal("fetch",vi.fn(async(input:RequestInfo|URL)=>String(input).includes("history")?Response.json({uptime:null,checks:[],nextCursor:null,incidents:[],buckets:[]}):Response.json({monitors:[monitor],capacity:{used:1,limit:40},discordConfigured:false})));render(<App/>);expect(await screen.findByRole("dialog",{name:"Linked"})).toBeInTheDocument();expect(globalThis.location.search).toBe("?monitor=1");fireEvent.click(screen.getByRole("button",{name:"Close details"}));expect(globalThis.location.search).toBe("");cleanup();globalThis.history.replaceState(null,"","/?monitor=999");render(<App/>);await screen.findByRole("button",{name:/Open Linked/});await waitFor(()=>expect(globalThis.location.search).toBe(""));expect(screen.queryByRole("dialog",{name:"Linked"})).not.toBeInTheDocument();});
  it("ignores a reversed stale history response",async()=>{const monitors=[1,2].map((id)=>({id,name:`Monitor ${id}`,url:`https://site-${id}.example/`,hostname:`site-${id}.example`,enabled:true,status:"up" as const,latestLatencyMs:20,latestStatusCode:200,lastCheckedAt:null,uptime24h:null,uptime30d:null,scheduleSlot:id-1}));const resolvers=new Map<number,(response:Response)=>void>();const fetcher=vi.fn((input:RequestInfo|URL)=>{const value=String(input);if(!value.includes("history"))return Promise.resolve(Response.json({monitors,capacity:{used:2,limit:40},discordConfigured:false}));const id=Number(value.match(/monitors\/(\d+)/)?.[1]);return new Promise<Response>((resolve)=>resolvers.set(id,resolve));});vi.stubGlobal("fetch",fetcher);render(<App/>);fireEvent.click(await screen.findByRole("button",{name:/Open Monitor 1/}));await waitFor(()=>expect(resolvers.has(1)).toBe(true));fireEvent.click(screen.getByRole("button",{name:/Open Monitor 2/}));await waitFor(()=>expect(resolvers.has(2)).toBe(true));resolvers.get(2)?.(Response.json({uptime:22,checks:[],nextCursor:null,incidents:[],buckets:[]}));expect(await screen.findByText("22.00%")).toBeInTheDocument();resolvers.get(1)?.(Response.json({uptime:11,checks:[],nextCursor:null,incidents:[],buckets:[]}));await Promise.resolve();expect(screen.queryByText("11.00%")).not.toBeInTheDocument();expect(screen.getByText("22.00%")).toBeInTheDocument();});
  it("traps dialog focus, closes with Escape, restores focus, and exposes one modal",async()=>{vi.stubGlobal("fetch",vi.fn(async()=>Response.json({monitors:[],capacity:{used:0,limit:40},discordConfigured:false})));render(<App/>);const opener=(await screen.findAllByRole("button",{name:"Add monitor"}))[0];opener.focus();fireEvent.click(opener);const dialog=screen.getByRole("dialog",{name:"Add monitor"});const name=screen.getByLabelText("Name");expect(name).toHaveFocus();const end=dialog.querySelector<HTMLElement>("[data-focus-end]");if(!end)throw new Error("focus boundary missing");end.focus();expect(name).toHaveFocus();fireEvent.keyDown(dialog,{key:"Escape",code:"Escape"});expect(screen.queryByRole("dialog",{name:"Add monitor"})).not.toBeInTheDocument();await waitFor(()=>expect(opener).toHaveFocus());});
});
