import { readFile } from "node:fs/promises";
import { Miniflare } from "miniflare";
import { generateKeyPair,SignJWT } from "jose";
import { afterEach,describe,expect,it,vi } from "vitest";
import { createMonitor,getMonitor,history,recordObservation } from "../src/worker/db";
import { authorize } from "../src/worker/auth";
import { runMonitorCheck } from "../src/worker/checker";
import type { Env } from "../src/worker/env";
import { drainOneNotification,retryDelay } from "../src/worker/notifications";
import { runRetentionOnceDaily } from "../src/worker/retention";
import { routeApi } from "../src/worker/router";
import { runScheduled } from "../src/worker/scheduler";

const instances:Miniflare[]=[];
async function database():Promise<D1Database>{
  const mf=new Miniflare({modules:true,script:"export default {}",d1Databases:{DB:crypto.randomUUID()}});instances.push(mf);
  const db=await mf.getD1Database("DB");const migration=(await readFile(new URL("../migrations/0001_initial.sql",import.meta.url),"utf8")).replace("PRAGMA foreign_keys = ON;","").replace(/\n\s*/g," ");await db.exec(migration);return db;
}
function environment(db:D1Database,discord=true):Env{return{DB:db,ASSETS:{fetch} as Fetcher,ENVIRONMENT:"local",ACCESS_TEAM_DOMAIN:"https://owner.cloudflareaccess.com",ACCESS_AUD:"audience",DASHBOARD_URL:"https://status.example",...(discord?{DISCORD_WEBHOOK_URL:"https://discord.example/webhook"}:{})};}
async function insertCheck(db:D1Database,monitorId:number,id:string,checkedAt:string,success:boolean):Promise<void>{
  const token=crypto.randomUUID();await db.prepare("UPDATE monitors SET observation_token=? WHERE id=?").bind(token,monitorId).run();await db.prepare("INSERT INTO checks(id,monitor_id,observation_token,checked_at,success,status_code,latency_ms,error_code) VALUES(?,?,?,?,?,?,?,?)").bind(id,monitorId,token,checkedAt,success?1:0,success?200:500,20,success?null:"http_error").run();
}
afterEach(async()=>{vi.unstubAllGlobals();await Promise.all(instances.splice(0).map((mf)=>mf.dispose()));});

describe("D1 history and retention",()=>{
  it("uses every completed check for exact 24h and 30d uptime while paging recent rows",async()=>{const db=await database();const monitor=await createMonitor(db,"Example","https://example.com/");const now=new Date("2026-07-22T12:00:00.000Z");const statements=[];for(let index=0;index<600;index+=1){const checkedAt=new Date(now.valueOf()-index*60*60*1000).toISOString();const token=`token-${index}`;statements.push(db.prepare("UPDATE monitors SET observation_token=? WHERE id=?").bind(token,monitor.id),db.prepare("INSERT INTO checks(id,monitor_id,observation_token,checked_at,success,status_code,latency_ms,error_code) VALUES(?,?,?,?,1,200,20,NULL)").bind(`check-${index}`,monitor.id,token,checkedAt));}await db.batch(statements);await insertCheck(db,monitor.id,"failed-24h",new Date(now.valueOf()-23*60*60*1000).toISOString(),false);await insertCheck(db,monitor.id,"failed-30d",new Date(now.valueOf()-20*24*60*60*1000).toISOString(),false);const day=await history(db,monitor.id,"24h",undefined,now);const month=await history(db,monitor.id,"30d",undefined,now);expect(day.uptime).toBe(96.15);expect(month.uptime).toBe(99.67);expect(month.checks).toHaveLength(100);expect(month.nextCursor).not.toBeNull();expect(day.buckets).toHaveLength(96);expect(day.buckets[0].at).toBe("2026-07-21T12:00:00.000Z");expect(month.buckets.at(-1)?.at).toBe("2026-07-22T04:30:00.000Z");},15_000);
  it("keeps exact cutoff rows and deletes only timestamps older than retention",async()=>{const db=await database();const monitor=await createMonitor(db,"Boundary","https://boundary.example/");const now=new Date("2026-07-22T12:00:00.000Z");await insertCheck(db,monitor.id,"inside",new Date(now.valueOf()-30*24*60*60*1000).toISOString(),true);await insertCheck(db,monitor.id,"outside",new Date(now.valueOf()-30*24*60*60*1000-1000).toISOString(),false);expect((await history(db,monitor.id,"30d",undefined,now)).checks.map((row)=>row.id)).toEqual(["inside"]);await runRetentionOnceDaily(environment(db),now);expect(await db.prepare("SELECT id FROM checks ORDER BY id").all<{id:string}>()).toMatchObject({results:[{id:"inside"}]});});
  it("paginates same-second rows without loss and includes incidents overlapping the window",async()=>{const db=await database();const monitor=await createMonitor(db,"Paging","https://paging.example/");const checkedAt="2026-07-22T11:30:00.000Z";const statements=[];for(let index=0;index<105;index+=1){const token=`page-token-${index}`;statements.push(db.prepare("UPDATE monitors SET observation_token=? WHERE id=?").bind(token,monitor.id),db.prepare("INSERT INTO checks(id,monitor_id,observation_token,checked_at,success,status_code,latency_ms,error_code) VALUES(?,?,?,?,1,200,20,NULL)").bind(`same-${String(index).padStart(3,"0")}`,monitor.id,token,checkedAt));}await db.batch(statements);await db.prepare("INSERT INTO incidents(monitor_id,started_at,resolved_at) VALUES(?,?,?),(?,?,?)").bind(monitor.id,"2026-07-20T00:00:00.000Z","2026-07-22T11:00:00.000Z",monitor.id,"2026-07-19T00:00:00.000Z","2026-07-21T10:00:00.000Z").run();const now=new Date("2026-07-22T12:00:00.000Z");const first=await history(db,monitor.id,"24h",undefined,now);if(!first.nextCursor)throw new Error("cursor missing");const second=await history(db,monitor.id,"24h",first.nextCursor,now);expect(new Set([...first.checks,...second.checks].map((row)=>row.id)).size).toBe(105);expect(second.checks).toHaveLength(5);expect(first.incidents).toHaveLength(1);expect(first.incidents[0].resolvedAt).toBe("2026-07-22T11:00:00.000Z");},10_000);
});

describe("checker and scheduled budget",()=>{
  it("reapplies one completed HTTP observation after a version conflict without refetching",async()=>{const db=await database();const monitor=await createMonitor(db,"Conflict","https://conflict.example/");const fetcher=vi.fn<typeof fetch>(async()=>{await db.prepare("UPDATE monitors SET version=version+1 WHERE id=?").bind(monitor.id).run();return new Response(null,{status:200});});await runMonitorCheck(environment(db),monitor.id,{fetcher});expect(fetcher).toHaveBeenCalledTimes(1);expect(await db.prepare("SELECT COUNT(*) count FROM checks WHERE monitor_id=?").bind(monitor.id).first<{count:number}>()).toEqual({count:1});});
  it("persists four overlapping observations once without letting an older result overwrite the newest",async()=>{const db=await database();const monitor=await createMonitor(db,"Concurrent","https://concurrent.example/");let arrivals=0;let release:()=>void=()=>undefined;const gate=new Promise<void>((resolve)=>{release=resolve;});const calls=Array.from({length:4},(_,index)=>{const fetcher=vi.fn<typeof fetch>(async()=>{arrivals+=1;if(arrivals===4)release();await gate;return new Response(null,{status:201+index});});return{fetcher,promise:runMonitorCheck(environment(db),monitor.id,{fetcher,now:()=>Date.parse(`2026-07-22T12:00:0${index}.000Z`)})};});await Promise.all(calls.map((entry)=>entry.promise));expect(calls.map((entry)=>entry.fetcher.mock.calls.length)).toEqual([1,1,1,1]);expect(await db.prepare("SELECT COUNT(*) count FROM checks WHERE monitor_id=?").bind(monitor.id).first<{count:number}>()).toEqual({count:4});expect(await db.prepare("SELECT last_checked_at,latest_status_code FROM monitors WHERE id=?").bind(monitor.id).first<{last_checked_at:string;latest_status_code:number}>()).toEqual({last_checked_at:"2026-07-22T12:00:03.000Z",latest_status_code:204});},10_000);
  it("runs eight worst-case redirects plus one Discord attempt within 17 external requests",async()=>{const db=await database();for(let index=0;index<40;index+=1)await createMonitor(db,`Monitor ${index}`,`https://site-${index}.example/`);await expect(createMonitor(db,"Overflow","https://overflow.example/")).rejects.toThrow("monitor_limit_reached");const first=await getMonitor(db,1);if(!first)throw new Error("monitor missing");await recordObservation(db,first,{success:false,statusCode:500,latencyMs:10,errorCode:"http_error",checkedAt:"2020-01-01T11:50:00.000Z"});const second=await getMonitor(db,1);if(!second)throw new Error("monitor missing");await recordObservation(db,second,{success:false,statusCode:500,latencyMs:10,errorCode:"http_error",checkedAt:"2020-01-01T11:55:00.000Z"});let requests=0;const fetcher=vi.fn<typeof fetch>(async(input)=>{requests+=1;const value=String(input);if(value.startsWith("https://discord.example"))return new Response(null,{status:204});if(value.includes("/redirected"))return new Response(null,{status:200});return new Response(null,{status:302,headers:{location:"/redirected"}});});vi.stubGlobal("fetch",fetcher);await runScheduled(environment(db),new Date("2026-07-22T12:00:00.000Z"));expect(requests).toBe(17);expect(requests).toBeLessThanOrEqual(17);},15_000);
});

describe("Discord claims and API errors",()=>{
  it("claims overlapping delivery once and includes failure and recovery details",async()=>{const db=await database();const monitor=await createMonitor(db,"@Owner **site**","https://notify.example/");await insertCheck(db,monitor.id,"opening","2026-07-22T11:59:00.000Z",false);await db.prepare("INSERT INTO incidents(monitor_id,started_at,opening_check_id,down_next_attempt_at) VALUES(?,?,?,?)").bind(monitor.id,"2026-07-22T11:59:00.000Z","opening","2026-07-22T11:59:00.000Z").run();let release:()=>void=()=>undefined;const gate=new Promise<void>((resolve)=>{release=resolve;});const payloads:string[]=[];const fetcher=vi.fn<typeof fetch>(async(_input,init)=>{payloads.push(String(init?.body));await gate;return new Response(null,{status:204});});const clock=()=>new Date("2026-07-22T12:00:00.000Z");const first=drainOneNotification(environment(db),fetcher,clock);await vi.waitFor(()=>expect(fetcher).toHaveBeenCalledTimes(1));const second=await drainOneNotification(environment(db),fetcher,clock);release();expect(await first).toBe(true);expect(second).toBe(false);expect(payloads[0]).toContain("Failure: HTTP 500");expect(payloads[0]).not.toContain("@Owner");const incident=await db.prepare("SELECT id,down_attempts,down_delivered_at,down_claim_token FROM incidents").first<{id:number;down_attempts:number;down_delivered_at:string|null;down_claim_token:string|null}>();expect(incident).toMatchObject({down_attempts:1,down_delivered_at:"2026-07-22T12:00:00.000Z",down_claim_token:null});if(!incident)throw new Error("incident missing");await insertCheck(db,monitor.id,"closing","2026-07-22T12:01:00.000Z",true);await db.prepare("UPDATE incidents SET resolved_at=?,closing_check_id=?,recovery_next_attempt_at=? WHERE id=?").bind("2026-07-22T12:01:00.000Z","closing","2026-07-22T12:01:00.000Z",incident.id).run();expect(await drainOneNotification(environment(db),fetcher,()=>new Date("2026-07-22T12:02:00.000Z"))).toBe(true);expect(payloads[1]).toContain("Recovered in 20 ms");});
  it("reclaims an expired lease, backs off an HTTP failure, and drains the next backlog item",async()=>{const db=await database();const older=await createMonitor(db,"Older","https://older.example/");const newer=await createMonitor(db,"Newer","https://newer.example/");await db.prepare("INSERT INTO incidents(monitor_id,started_at,down_next_attempt_at,down_claim_token,down_claimed_until) VALUES(?,?,?,?,?),(?,?,?,?,?)").bind(older.id,"2026-07-22T11:00:00.000Z","2026-07-22T11:00:00.000Z","abandoned","2026-07-22T11:59:00.000Z",newer.id,"2026-07-22T11:30:00.000Z","2026-07-22T11:30:00.000Z",null,null).run();const names:string[]=[];const fetcher=vi.fn<typeof fetch>(async(_input,init)=>{names.push(String(init?.body));return names.length===1?new Response(null,{status:500,headers:{"retry-after":"60"}}):new Response(null,{status:204});});const clock=()=>new Date("2026-07-22T12:00:00.000Z");expect(await drainOneNotification(environment(db),fetcher,clock)).toBe(true);expect(await drainOneNotification(environment(db),fetcher,clock)).toBe(true);expect(await drainOneNotification(environment(db),fetcher,clock)).toBe(false);expect(names[0]).toContain("Older");expect(names[1]).toContain("Newer");expect(await db.prepare("SELECT down_attempts,down_next_attempt_at,down_error FROM incidents WHERE monitor_id=?").bind(older.id).first()).toEqual({down_attempts:1,down_next_attempt_at:"2026-07-22T12:01:00.000Z",down_error:"discord_http_500"});});
  it("honors numeric and HTTP-date Retry-After and returns stable API failures",async()=>{const now=Date.parse("2026-07-22T12:00:00.000Z");expect(retryDelay(new Response(null,{status:429,headers:{"retry-after":"12"}}),1,now)).toBe(12);expect(retryDelay(new Response(null,{status:429,headers:{"retry-after":"Wed, 22 Jul 2026 12:00:45 GMT"}}),1,now)).toBe(45);const db=await database();const env=environment(db,false);const ctx={waitUntil:()=>undefined,passThroughOnException:()=>undefined} as ExecutionContext;const malformed=await routeApi(new Request("https://status.example/api/monitors",{method:"POST",headers:{"content-type":"application/json"},body:"{"}),env,ctx);expect(await malformed.json()).toEqual({error:{code:"invalid_json",message:"Request body must contain valid JSON"}});const invalid=await routeApi(new Request("https://status.example/api/monitors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:"Bad",url:"file:///tmp/x"})}),env,ctx);expect(await invalid.json()).toMatchObject({error:{code:"invalid_url"}});await createMonitor(db,"One","https://one.example/");await createMonitor(db,"Two","https://two.example/");const duplicateCreate=await routeApi(new Request("https://status.example/api/monitors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:"Duplicate",url:"https://one.example/"})}),env,ctx);expect(await duplicateCreate.json()).toMatchObject({error:{code:"duplicate_url"}});const duplicate=await routeApi(new Request("https://status.example/api/monitors/2",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({url:"https://one.example/"})}),env,ctx);expect(duplicate.status).toBe(409);expect(await duplicate.json()).toEqual({error:{code:"duplicate_url",message:"That URL is already monitored"}});vi.stubGlobal("fetch",vi.fn(async()=>{throw new Error("secret network detail");}));const discordFailure=await routeApi(new Request("https://status.example/api/notifications/discord/test",{method:"POST"}),environment(db),ctx);expect(discordFailure.status).toBe(502);expect(await discordFailure.json()).toEqual({error:{code:"discord_delivery_failed",message:"Discord rejected the test notification"}});const unauthorized=await routeApi(new Request("https://status.example/api/monitors"),{...env,ENVIRONMENT:"LOCAL"},ctx);expect(unauthorized.status).toBe(401);});
  it("accepts only a temporally valid Access JWT with the exact issuer and audience",async()=>{const {publicKey,privateKey}=await generateKeyPair("ES256");const env={...environment(await database(),false),ENVIRONMENT:"production"};const issuer=env.ACCESS_TEAM_DOMAIN;const token=await new SignJWT({}).setProtectedHeader({alg:"ES256"}).setIssuer(issuer).setAudience(env.ACCESS_AUD).setIssuedAt().setExpirationTime("2m").sign(privateKey);const request=new Request("https://status.example/api/monitors",{headers:{"cf-access-jwt-assertion":token}});const key=async()=>publicKey;expect(await authorize(request,env,key)).toBe(true);const wrongAudience=await new SignJWT({}).setProtectedHeader({alg:"ES256"}).setIssuer(issuer).setAudience("wrong").setIssuedAt().setExpirationTime("2m").sign(privateKey);expect(await authorize(new Request(request,{headers:{"cf-access-jwt-assertion":wrongAudience}}),env,key)).toBe(false);const expired=await new SignJWT({}).setProtectedHeader({alg:"ES256"}).setIssuer(issuer).setAudience(env.ACCESS_AUD).setIssuedAt(1).setExpirationTime(2).sign(privateKey);expect(await authorize(new Request(request,{headers:{"cf-access-jwt-assertion":expired}}),env,key)).toBe(false);});
  it("routes CRUD, pause/resume, manual limits, and cascading delete through local D1",async()=>{const db=await database();const env=environment(db,false);const waits:Promise<unknown>[]=[];const ctx={waitUntil:(promise:Promise<unknown>)=>waits.push(promise),passThroughOnException:()=>undefined} as ExecutionContext;vi.stubGlobal("fetch",vi.fn(async()=>new Response(null,{status:200})));const create=await routeApi(new Request("https://status.example/api/monitors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:"Routed",url:"https://routed.example"})}),env,ctx);expect(create.status).toBe(201);const created=await create.json() as {id:number};await Promise.all(waits);const pause=await routeApi(new Request(`https://status.example/api/monitors/${created.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:false})}),env,ctx);expect(await pause.json()).toMatchObject({enabled:false,status:"paused"});expect((await routeApi(new Request(`https://status.example/api/monitors/${created.id}/check`,{method:"POST"}),env,ctx)).status).toBe(409);const resume=await routeApi(new Request(`https://status.example/api/monitors/${created.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:true})}),env,ctx);expect(await resume.json()).toMatchObject({enabled:true,status:"checking"});for(let attempt=0;attempt<3;attempt+=1)expect((await routeApi(new Request(`https://status.example/api/monitors/${created.id}/check`,{method:"POST"}),env,ctx)).status).toBe(202);expect((await routeApi(new Request(`https://status.example/api/monitors/${created.id}/check`,{method:"POST"}),env,ctx)).status).toBe(429);expect((await db.prepare("SELECT COUNT(*) count FROM checks WHERE monitor_id=?").bind(created.id).first<{count:number}>())?.count).toBeGreaterThan(0);await db.prepare("INSERT INTO incidents(monitor_id,started_at) VALUES(?,?)").bind(created.id,new Date().toISOString()).run();expect((await routeApi(new Request(`https://status.example/api/monitors/${created.id}`,{method:"DELETE"}),env,ctx)).status).toBe(204);expect(await db.prepare("SELECT COUNT(*) count FROM checks WHERE monitor_id=?").bind(created.id).first<{count:number}>()).toEqual({count:0});expect(await db.prepare("SELECT COUNT(*) count FROM incidents WHERE monitor_id=?").bind(created.id).first<{count:number}>()).toEqual({count:0});},10_000);
});
