/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FRouteImport } from './routes/f'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as FaviconDotsvgRouteImport } from './routes/favicon[.]svg'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as PRouteImport } from './routes/p'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as StatusRouteImport } from './routes/status'
import { Route as UploadsRouteImport } from './routes/uploads'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiExternalUploadsRouteImport } from './routes/api/external-uploads'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ArtifactsSplatRouteImport } from './routes/artifacts/$'
import { Route as ArtifactsIdRouteImport } from './routes/artifacts/$id'
import { Route as AssetsSplatRouteImport } from './routes/assets/$'
import { Route as FIdRouteImport } from './routes/f/$id'
import { Route as FilesIdRouteImport } from './routes/files/$id'
import { Route as HealthComponentRouteImport } from './routes/health/$component'
import { Route as ManageIndexRouteImport } from './routes/manage/index'
import { Route as ManageDocumentsRouteImport } from './routes/manage/documents'
import { Route as ManageStatusRouteImport } from './routes/manage/status'
import { Route as OpsSplatRouteImport } from './routes/ops/$'
import { Route as PSplatRouteImport } from './routes/p/$'
import { Route as PIdRouteImport } from './routes/p/$id'
import { Route as PublishCallbackRouteImport } from './routes/publish/callback'
import { Route as ReviewCallbackRouteImport } from './routes/review/callback'
import { Route as StatusPrivateRouteImport } from './routes/status/private'
import { Route as UploadsSplatRouteImport } from './routes/uploads/$'
import { Route as ApiAgentSplatRouteImport } from './routes/api/agent/$'
import { Route as ApiExternalUploadsSplatRouteImport } from './routes/api/external-uploads/$'
import { Route as ApiHeartbeatTowerRouteImport } from './routes/api/heartbeat/tower'
import { Route as ApiOpsSplatRouteImport } from './routes/api/ops/$'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiReviewSplatRouteImport } from './routes/api/review/$'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as FIdSplatRouteImport } from './routes/f/$id/$'
import { Route as FilesIdSplatRouteImport } from './routes/files/$id/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FRoute = FRouteImport.update({
  id: '/f',
  path: '/f',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDotsvgRoute = FaviconDotsvgRouteImport.update({
  id: '/favicon.svg',
  path: '/favicon.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const PRoute = PRouteImport.update({
  id: '/p',
  path: '/p',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadsRoute = UploadsRouteImport.update({
  id: '/uploads',
  path: '/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalUploadsRoute = ApiExternalUploadsRouteImport.update({
  id: '/api/external-uploads',
  path: '/api/external-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsSplatRoute = ArtifactsSplatRouteImport.update({
  id: '/artifacts/$',
  path: '/artifacts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIdRoute = ArtifactsIdRouteImport.update({
  id: '/artifacts/$id',
  path: '/artifacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FIdRoute = FIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FRoute,
} as any)
const FilesIdRoute = FilesIdRouteImport.update({
  id: '/files/$id',
  path: '/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthComponentRoute = HealthComponentRouteImport.update({
  id: '/$component',
  path: '/$component',
  getParentRoute: () => HealthRoute,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageDocumentsRoute = ManageDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ManageRoute,
} as any)
const ManageStatusRoute = ManageStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ManageRoute,
} as any)
const OpsSplatRoute = OpsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => OpsRoute,
} as any)
const PSplatRoute = PSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PRoute,
} as any)
const PIdRoute = PIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PRoute,
} as any)
const PublishCallbackRoute = PublishCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => PublishRoute,
} as any)
const ReviewCallbackRoute = ReviewCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ReviewRoute,
} as any)
const StatusPrivateRoute = StatusPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => StatusRoute,
} as any)
const UploadsSplatRoute = UploadsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => UploadsRoute,
} as any)
const ApiAgentSplatRoute = ApiAgentSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiExternalUploadsSplatRoute = ApiExternalUploadsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiExternalUploadsRoute,
} as any)
const ApiHeartbeatTowerRoute = ApiHeartbeatTowerRouteImport.update({
  id: '/api/heartbeat/tower',
  path: '/api/heartbeat/tower',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsSplatRoute = ApiOpsSplatRouteImport.update({
  id: '/api/ops/$',
  path: '/api/ops/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewSplatRoute = ApiReviewSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiReviewRoute,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const FIdSplatRoute = FIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => FIdRoute,
} as any)
const FilesIdSplatRoute = FilesIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => FilesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/f': typeof FRouteWithChildren
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/health': typeof HealthRouteWithChildren
  '/live': typeof LiveRoute
  '/manage': typeof ManageRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/p': typeof PRouteWithChildren
  '/publish': typeof PublishRouteWithChildren
  '/review': typeof ReviewRouteWithChildren
  '/status': typeof StatusRouteWithChildren
  '/uploads': typeof UploadsRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/external-uploads': typeof ApiExternalUploadsRouteWithChildren
  '/api/review': typeof ApiReviewRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/artifacts/$': typeof ArtifactsSplatRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/assets/$': typeof AssetsSplatRoute
  '/f/$id': typeof FIdRouteWithChildren
  '/files/$id': typeof FilesIdRouteWithChildren
  '/health/$component': typeof HealthComponentRoute
  '/manage/documents': typeof ManageDocumentsRoute
  '/manage/status': typeof ManageStatusRoute
  '/ops/$': typeof OpsSplatRoute
  '/p/$': typeof PSplatRoute
  '/p/$id': typeof PIdRoute
  '/publish/callback': typeof PublishCallbackRoute
  '/review/callback': typeof ReviewCallbackRoute
  '/status/private': typeof StatusPrivateRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/manage/': typeof ManageIndexRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/external-uploads/$': typeof ApiExternalUploadsSplatRoute
  '/api/heartbeat/tower': typeof ApiHeartbeatTowerRoute
  '/api/ops/$': typeof ApiOpsSplatRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/review/$': typeof ApiReviewSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/f/$id/$': typeof FIdSplatRoute
  '/files/$id/$': typeof FilesIdSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/f': typeof FRouteWithChildren
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/health': typeof HealthRouteWithChildren
  '/live': typeof LiveRoute
  '/ops': typeof OpsRouteWithChildren
  '/p': typeof PRouteWithChildren
  '/publish': typeof PublishRouteWithChildren
  '/review': typeof ReviewRouteWithChildren
  '/status': typeof StatusRouteWithChildren
  '/uploads': typeof UploadsRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/external-uploads': typeof ApiExternalUploadsRouteWithChildren
  '/api/review': typeof ApiReviewRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/artifacts/$': typeof ArtifactsSplatRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/assets/$': typeof AssetsSplatRoute
  '/f/$id': typeof FIdRouteWithChildren
  '/files/$id': typeof FilesIdRouteWithChildren
  '/health/$component': typeof HealthComponentRoute
  '/manage/documents': typeof ManageDocumentsRoute
  '/manage/status': typeof ManageStatusRoute
  '/ops/$': typeof OpsSplatRoute
  '/p/$': typeof PSplatRoute
  '/p/$id': typeof PIdRoute
  '/publish/callback': typeof PublishCallbackRoute
  '/review/callback': typeof ReviewCallbackRoute
  '/status/private': typeof StatusPrivateRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/manage': typeof ManageIndexRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/external-uploads/$': typeof ApiExternalUploadsSplatRoute
  '/api/heartbeat/tower': typeof ApiHeartbeatTowerRoute
  '/api/ops/$': typeof ApiOpsSplatRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/review/$': typeof ApiReviewSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/f/$id/$': typeof FIdSplatRoute
  '/files/$id/$': typeof FilesIdSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/f': typeof FRouteWithChildren
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/health': typeof HealthRouteWithChildren
  '/live': typeof LiveRoute
  '/manage': typeof ManageRouteWithChildren
  '/ops': typeof OpsRouteWithChildren
  '/p': typeof PRouteWithChildren
  '/publish': typeof PublishRouteWithChildren
  '/review': typeof ReviewRouteWithChildren
  '/status': typeof StatusRouteWithChildren
  '/uploads': typeof UploadsRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/external-uploads': typeof ApiExternalUploadsRouteWithChildren
  '/api/review': typeof ApiReviewRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/artifacts/$': typeof ArtifactsSplatRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/assets/$': typeof AssetsSplatRoute
  '/f/$id': typeof FIdRouteWithChildren
  '/files/$id': typeof FilesIdRouteWithChildren
  '/health/$component': typeof HealthComponentRoute
  '/manage/documents': typeof ManageDocumentsRoute
  '/manage/status': typeof ManageStatusRoute
  '/ops/$': typeof OpsSplatRoute
  '/p/$': typeof PSplatRoute
  '/p/$id': typeof PIdRoute
  '/publish/callback': typeof PublishCallbackRoute
  '/review/callback': typeof ReviewCallbackRoute
  '/status/private': typeof StatusPrivateRoute
  '/uploads/$': typeof UploadsSplatRoute
  '/manage/': typeof ManageIndexRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/external-uploads/$': typeof ApiExternalUploadsSplatRoute
  '/api/heartbeat/tower': typeof ApiHeartbeatTowerRoute
  '/api/ops/$': typeof ApiOpsSplatRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/review/$': typeof ApiReviewSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/f/$id/$': typeof FIdSplatRoute
  '/files/$id/$': typeof FilesIdSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/f'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/health'
    | '/live'
    | '/manage'
    | '/ops'
    | '/p'
    | '/publish'
    | '/review'
    | '/status'
    | '/uploads'
    | '/api/agent'
    | '/api/external-uploads'
    | '/api/review'
    | '/api/uploads'
    | '/artifacts/$'
    | '/artifacts/$id'
    | '/assets/$'
    | '/f/$id'
    | '/files/$id'
    | '/health/$component'
    | '/manage/documents'
    | '/manage/status'
    | '/ops/$'
    | '/p/$'
    | '/p/$id'
    | '/publish/callback'
    | '/review/callback'
    | '/status/private'
    | '/uploads/$'
    | '/manage/'
    | '/api/agent/$'
    | '/api/external-uploads/$'
    | '/api/heartbeat/tower'
    | '/api/ops/$'
    | '/api/public/catalog'
    | '/api/review/$'
    | '/api/uploads/$'
    | '/f/$id/$'
    | '/files/$id/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/f'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/health'
    | '/live'
    | '/ops'
    | '/p'
    | '/publish'
    | '/review'
    | '/status'
    | '/uploads'
    | '/api/agent'
    | '/api/external-uploads'
    | '/api/review'
    | '/api/uploads'
    | '/artifacts/$'
    | '/artifacts/$id'
    | '/assets/$'
    | '/f/$id'
    | '/files/$id'
    | '/health/$component'
    | '/manage/documents'
    | '/manage/status'
    | '/ops/$'
    | '/p/$'
    | '/p/$id'
    | '/publish/callback'
    | '/review/callback'
    | '/status/private'
    | '/uploads/$'
    | '/manage'
    | '/api/agent/$'
    | '/api/external-uploads/$'
    | '/api/heartbeat/tower'
    | '/api/ops/$'
    | '/api/public/catalog'
    | '/api/review/$'
    | '/api/uploads/$'
    | '/f/$id/$'
    | '/files/$id/$'
  id:
    | '__root__'
    | '/'
    | '/f'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/health'
    | '/live'
    | '/manage'
    | '/ops'
    | '/p'
    | '/publish'
    | '/review'
    | '/status'
    | '/uploads'
    | '/api/agent'
    | '/api/external-uploads'
    | '/api/review'
    | '/api/uploads'
    | '/artifacts/$'
    | '/artifacts/$id'
    | '/assets/$'
    | '/f/$id'
    | '/files/$id'
    | '/health/$component'
    | '/manage/documents'
    | '/manage/status'
    | '/ops/$'
    | '/p/$'
    | '/p/$id'
    | '/publish/callback'
    | '/review/callback'
    | '/status/private'
    | '/uploads/$'
    | '/manage/'
    | '/api/agent/$'
    | '/api/external-uploads/$'
    | '/api/heartbeat/tower'
    | '/api/ops/$'
    | '/api/public/catalog'
    | '/api/review/$'
    | '/api/uploads/$'
    | '/f/$id/$'
    | '/files/$id/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FRoute: typeof FRouteWithChildren
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  FaviconDotsvgRoute: typeof FaviconDotsvgRoute
  HealthRoute: typeof HealthRouteWithChildren
  LiveRoute: typeof LiveRoute
  ManageRoute: typeof ManageRouteWithChildren
  OpsRoute: typeof OpsRouteWithChildren
  PRoute: typeof PRouteWithChildren
  PublishRoute: typeof PublishRouteWithChildren
  ReviewRoute: typeof ReviewRouteWithChildren
  StatusRoute: typeof StatusRouteWithChildren
  UploadsRoute: typeof UploadsRouteWithChildren
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  ApiExternalUploadsRoute: typeof ApiExternalUploadsRouteWithChildren
  ApiReviewRoute: typeof ApiReviewRouteWithChildren
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ArtifactsSplatRoute: typeof ArtifactsSplatRoute
  ArtifactsIdRoute: typeof ArtifactsIdRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  FilesIdRoute: typeof FilesIdRouteWithChildren
  ApiHeartbeatTowerRoute: typeof ApiHeartbeatTowerRoute
  ApiOpsSplatRoute: typeof ApiOpsSplatRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f': {
      id: '/f'
      path: '/f'
      fullPath: '/f'
      preLoaderRoute: typeof FRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.svg': {
      id: '/favicon.svg'
      path: '/favicon.svg'
      fullPath: '/favicon.svg'
      preLoaderRoute: typeof FaviconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p': {
      id: '/p'
      path: '/p'
      fullPath: '/p'
      preLoaderRoute: typeof PRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uploads': {
      id: '/uploads'
      path: '/uploads'
      fullPath: '/uploads'
      preLoaderRoute: typeof UploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-uploads': {
      id: '/api/external-uploads'
      path: '/api/external-uploads'
      fullPath: '/api/external-uploads'
      preLoaderRoute: typeof ApiExternalUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$': {
      id: '/artifacts/$'
      path: '/artifacts/$'
      fullPath: '/artifacts/$'
      preLoaderRoute: typeof ArtifactsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$id': {
      id: '/artifacts/$id'
      path: '/artifacts/$id'
      fullPath: '/artifacts/$id'
      preLoaderRoute: typeof ArtifactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/f/$id': {
      id: '/f/$id'
      path: '/$id'
      fullPath: '/f/$id'
      preLoaderRoute: typeof FIdRouteImport
      parentRoute: typeof FRoute
    }
    '/files/$id': {
      id: '/files/$id'
      path: '/files/$id'
      fullPath: '/files/$id'
      preLoaderRoute: typeof FilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$component': {
      id: '/health/$component'
      path: '/$component'
      fullPath: '/health/$component'
      preLoaderRoute: typeof HealthComponentRouteImport
      parentRoute: typeof HealthRoute
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/documents': {
      id: '/manage/documents'
      path: '/documents'
      fullPath: '/manage/documents'
      preLoaderRoute: typeof ManageDocumentsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/status': {
      id: '/manage/status'
      path: '/status'
      fullPath: '/manage/status'
      preLoaderRoute: typeof ManageStatusRouteImport
      parentRoute: typeof ManageRoute
    }
    '/ops/$': {
      id: '/ops/$'
      path: '/$'
      fullPath: '/ops/$'
      preLoaderRoute: typeof OpsSplatRouteImport
      parentRoute: typeof OpsRoute
    }
    '/p/$': {
      id: '/p/$'
      path: '/$'
      fullPath: '/p/$'
      preLoaderRoute: typeof PSplatRouteImport
      parentRoute: typeof PRoute
    }
    '/p/$id': {
      id: '/p/$id'
      path: '/$id'
      fullPath: '/p/$id'
      preLoaderRoute: typeof PIdRouteImport
      parentRoute: typeof PRoute
    }
    '/publish/callback': {
      id: '/publish/callback'
      path: '/callback'
      fullPath: '/publish/callback'
      preLoaderRoute: typeof PublishCallbackRouteImport
      parentRoute: typeof PublishRoute
    }
    '/review/callback': {
      id: '/review/callback'
      path: '/callback'
      fullPath: '/review/callback'
      preLoaderRoute: typeof ReviewCallbackRouteImport
      parentRoute: typeof ReviewRoute
    }
    '/status/private': {
      id: '/status/private'
      path: '/private'
      fullPath: '/status/private'
      preLoaderRoute: typeof StatusPrivateRouteImport
      parentRoute: typeof StatusRoute
    }
    '/uploads/$': {
      id: '/uploads/$'
      path: '/$'
      fullPath: '/uploads/$'
      preLoaderRoute: typeof UploadsSplatRouteImport
      parentRoute: typeof UploadsRoute
    }
    '/api/agent/$': {
      id: '/api/agent/$'
      path: '/$'
      fullPath: '/api/agent/$'
      preLoaderRoute: typeof ApiAgentSplatRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/external-uploads/$': {
      id: '/api/external-uploads/$'
      path: '/$'
      fullPath: '/api/external-uploads/$'
      preLoaderRoute: typeof ApiExternalUploadsSplatRouteImport
      parentRoute: typeof ApiExternalUploadsRoute
    }
    '/api/heartbeat/tower': {
      id: '/api/heartbeat/tower'
      path: '/api/heartbeat/tower'
      fullPath: '/api/heartbeat/tower'
      preLoaderRoute: typeof ApiHeartbeatTowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/$': {
      id: '/api/ops/$'
      path: '/api/ops/$'
      fullPath: '/api/ops/$'
      preLoaderRoute: typeof ApiOpsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/$': {
      id: '/api/review/$'
      path: '/$'
      fullPath: '/api/review/$'
      preLoaderRoute: typeof ApiReviewSplatRouteImport
      parentRoute: typeof ApiReviewRoute
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/f/$id/$': {
      id: '/f/$id/$'
      path: '/$'
      fullPath: '/f/$id/$'
      preLoaderRoute: typeof FIdSplatRouteImport
      parentRoute: typeof FIdRoute
    }
    '/files/$id/$': {
      id: '/files/$id/$'
      path: '/$'
      fullPath: '/files/$id/$'
      preLoaderRoute: typeof FilesIdSplatRouteImport
      parentRoute: typeof FilesIdRoute
    }
  }
}

interface FIdRouteChildren {
  FIdSplatRoute: typeof FIdSplatRoute
}

const FIdRouteChildren: FIdRouteChildren = {
  FIdSplatRoute: FIdSplatRoute,
}

const FIdRouteWithChildren = FIdRoute._addFileChildren(FIdRouteChildren)

interface FRouteChildren {
  FIdRoute: typeof FIdRouteWithChildren
}

const FRouteChildren: FRouteChildren = {
  FIdRoute: FIdRouteWithChildren,
}

const FRouteWithChildren = FRoute._addFileChildren(FRouteChildren)

interface HealthRouteChildren {
  HealthComponentRoute: typeof HealthComponentRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthComponentRoute: HealthComponentRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

interface ManageRouteChildren {
  ManageDocumentsRoute: typeof ManageDocumentsRoute
  ManageStatusRoute: typeof ManageStatusRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageDocumentsRoute: ManageDocumentsRoute,
  ManageStatusRoute: ManageStatusRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

interface OpsRouteChildren {
  OpsSplatRoute: typeof OpsSplatRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsSplatRoute: OpsSplatRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface PRouteChildren {
  PSplatRoute: typeof PSplatRoute
  PIdRoute: typeof PIdRoute
}

const PRouteChildren: PRouteChildren = {
  PSplatRoute: PSplatRoute,
  PIdRoute: PIdRoute,
}

const PRouteWithChildren = PRoute._addFileChildren(PRouteChildren)

interface PublishRouteChildren {
  PublishCallbackRoute: typeof PublishCallbackRoute
}

const PublishRouteChildren: PublishRouteChildren = {
  PublishCallbackRoute: PublishCallbackRoute,
}

const PublishRouteWithChildren =
  PublishRoute._addFileChildren(PublishRouteChildren)

interface ReviewRouteChildren {
  ReviewCallbackRoute: typeof ReviewCallbackRoute
}

const ReviewRouteChildren: ReviewRouteChildren = {
  ReviewCallbackRoute: ReviewCallbackRoute,
}

const ReviewRouteWithChildren =
  ReviewRoute._addFileChildren(ReviewRouteChildren)

interface StatusRouteChildren {
  StatusPrivateRoute: typeof StatusPrivateRoute
}

const StatusRouteChildren: StatusRouteChildren = {
  StatusPrivateRoute: StatusPrivateRoute,
}

const StatusRouteWithChildren =
  StatusRoute._addFileChildren(StatusRouteChildren)

interface UploadsRouteChildren {
  UploadsSplatRoute: typeof UploadsSplatRoute
}

const UploadsRouteChildren: UploadsRouteChildren = {
  UploadsSplatRoute: UploadsSplatRoute,
}

const UploadsRouteWithChildren =
  UploadsRoute._addFileChildren(UploadsRouteChildren)

interface ApiAgentRouteChildren {
  ApiAgentSplatRoute: typeof ApiAgentSplatRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentSplatRoute: ApiAgentSplatRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

interface ApiExternalUploadsRouteChildren {
  ApiExternalUploadsSplatRoute: typeof ApiExternalUploadsSplatRoute
}

const ApiExternalUploadsRouteChildren: ApiExternalUploadsRouteChildren = {
  ApiExternalUploadsSplatRoute: ApiExternalUploadsSplatRoute,
}

const ApiExternalUploadsRouteWithChildren =
  ApiExternalUploadsRoute._addFileChildren(ApiExternalUploadsRouteChildren)

interface ApiReviewRouteChildren {
  ApiReviewSplatRoute: typeof ApiReviewSplatRoute
}

const ApiReviewRouteChildren: ApiReviewRouteChildren = {
  ApiReviewSplatRoute: ApiReviewSplatRoute,
}

const ApiReviewRouteWithChildren = ApiReviewRoute._addFileChildren(
  ApiReviewRouteChildren,
)

interface ApiUploadsRouteChildren {
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

interface FilesIdRouteChildren {
  FilesIdSplatRoute: typeof FilesIdSplatRoute
}

const FilesIdRouteChildren: FilesIdRouteChildren = {
  FilesIdSplatRoute: FilesIdSplatRoute,
}

const FilesIdRouteWithChildren =
  FilesIdRoute._addFileChildren(FilesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FRoute: FRouteWithChildren,
  FaviconDoticoRoute: FaviconDoticoRoute,
  FaviconDotsvgRoute: FaviconDotsvgRoute,
  HealthRoute: HealthRouteWithChildren,
  LiveRoute: LiveRoute,
  ManageRoute: ManageRouteWithChildren,
  OpsRoute: OpsRouteWithChildren,
  PRoute: PRouteWithChildren,
  PublishRoute: PublishRouteWithChildren,
  ReviewRoute: ReviewRouteWithChildren,
  StatusRoute: StatusRouteWithChildren,
  UploadsRoute: UploadsRouteWithChildren,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  ApiExternalUploadsRoute: ApiExternalUploadsRouteWithChildren,
  ApiReviewRoute: ApiReviewRouteWithChildren,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ArtifactsSplatRoute: ArtifactsSplatRoute,
  ArtifactsIdRoute: ArtifactsIdRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  FilesIdRoute: FilesIdRouteWithChildren,
  ApiHeartbeatTowerRoute: ApiHeartbeatTowerRoute,
  ApiOpsSplatRoute: ApiOpsSplatRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
