/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as FaviconDotsvgRouteImport } from './routes/favicon[.]svg'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LiveRouteImport } from './routes/live'
import { Route as ManageRouteImport } from './routes/manage'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as ReviewRouteImport } from './routes/review'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiExternalUploadsRouteImport } from './routes/api/external-uploads'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ArtifactsSplatRouteImport } from './routes/artifacts/$'
import { Route as ArtifactsIdRouteImport } from './routes/artifacts/$id'
import { Route as AssetsSplatRouteImport } from './routes/assets/$'
import { Route as FilesIdRouteImport } from './routes/files/$id'
import { Route as HealthComponentRouteImport } from './routes/health/$component'
import { Route as ManageIndexRouteImport } from './routes/manage/index'
import { Route as ManageDocumentsRouteImport } from './routes/manage/documents'
import { Route as ManageStatusRouteImport } from './routes/manage/status'
import { Route as ToolsPrivateRouteImport } from './routes/tools/private'
import { Route as ApiAgentSplatRouteImport } from './routes/api/agent/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiExternalUploadsSplatRouteImport } from './routes/api/external-uploads/$'
import { Route as ApiHeartbeatTowerRouteImport } from './routes/api/heartbeat/tower'
import { Route as ApiOpsSplatRouteImport } from './routes/api/ops/$'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiReviewSplatRouteImport } from './routes/api/review/$'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as FilesIdSplatRouteImport } from './routes/files/$id/$'
import { Route as ToolsPrivateMoneyRouteImport } from './routes/tools/private/money'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDotsvgRoute = FaviconDotsvgRouteImport.update({
  id: '/favicon.svg',
  path: '/favicon.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const ManageRoute = ManageRouteImport.update({
  id: '/manage',
  path: '/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalUploadsRoute = ApiExternalUploadsRouteImport.update({
  id: '/api/external-uploads',
  path: '/api/external-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsSplatRoute = ArtifactsSplatRouteImport.update({
  id: '/artifacts/$',
  path: '/artifacts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIdRoute = ArtifactsIdRouteImport.update({
  id: '/artifacts/$id',
  path: '/artifacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIdRoute = FilesIdRouteImport.update({
  id: '/files/$id',
  path: '/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthComponentRoute = HealthComponentRouteImport.update({
  id: '/$component',
  path: '/$component',
  getParentRoute: () => HealthRoute,
} as any)
const ManageIndexRoute = ManageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ManageRoute,
} as any)
const ManageDocumentsRoute = ManageDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ManageRoute,
} as any)
const ManageStatusRoute = ManageStatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => ManageRoute,
} as any)
const ToolsPrivateRoute = ToolsPrivateRouteImport.update({
  id: '/private',
  path: '/private',
  getParentRoute: () => ToolsRoute,
} as any)
const ApiAgentSplatRoute = ApiAgentSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalUploadsSplatRoute = ApiExternalUploadsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiExternalUploadsRoute,
} as any)
const ApiHeartbeatTowerRoute = ApiHeartbeatTowerRouteImport.update({
  id: '/api/heartbeat/tower',
  path: '/api/heartbeat/tower',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsSplatRoute = ApiOpsSplatRouteImport.update({
  id: '/api/ops/$',
  path: '/api/ops/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewSplatRoute = ApiReviewSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiReviewRoute,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const FilesIdSplatRoute = FilesIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => FilesIdRoute,
} as any)
const ToolsPrivateMoneyRoute = ToolsPrivateMoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => ToolsPrivateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/health': typeof HealthRouteWithChildren
  '/live': typeof LiveRoute
  '/manage': typeof ManageRouteWithChildren
  '/publish': typeof PublishRoute
  '/review': typeof ReviewRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/tools': typeof ToolsRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/external-uploads': typeof ApiExternalUploadsRouteWithChildren
  '/api/review': typeof ApiReviewRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/artifacts/$': typeof ArtifactsSplatRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/assets/$': typeof AssetsSplatRoute
  '/files/$id': typeof FilesIdRouteWithChildren
  '/health/$component': typeof HealthComponentRoute
  '/manage/documents': typeof ManageDocumentsRoute
  '/manage/status': typeof ManageStatusRoute
  '/tools/private': typeof ToolsPrivateRouteWithChildren
  '/manage/': typeof ManageIndexRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/external-uploads/$': typeof ApiExternalUploadsSplatRoute
  '/api/heartbeat/tower': typeof ApiHeartbeatTowerRoute
  '/api/ops/$': typeof ApiOpsSplatRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/review/$': typeof ApiReviewSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/files/$id/$': typeof FilesIdSplatRoute
  '/tools/private/money': typeof ToolsPrivateMoneyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/health': typeof HealthRouteWithChildren
  '/live': typeof LiveRoute
  '/publish': typeof PublishRoute
  '/review': typeof ReviewRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/tools': typeof ToolsRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/external-uploads': typeof ApiExternalUploadsRouteWithChildren
  '/api/review': typeof ApiReviewRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/artifacts/$': typeof ArtifactsSplatRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/assets/$': typeof AssetsSplatRoute
  '/files/$id': typeof FilesIdRouteWithChildren
  '/health/$component': typeof HealthComponentRoute
  '/manage/documents': typeof ManageDocumentsRoute
  '/manage/status': typeof ManageStatusRoute
  '/tools/private': typeof ToolsPrivateRouteWithChildren
  '/manage': typeof ManageIndexRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/external-uploads/$': typeof ApiExternalUploadsSplatRoute
  '/api/heartbeat/tower': typeof ApiHeartbeatTowerRoute
  '/api/ops/$': typeof ApiOpsSplatRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/review/$': typeof ApiReviewSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/files/$id/$': typeof FilesIdSplatRoute
  '/tools/private/money': typeof ToolsPrivateMoneyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/health': typeof HealthRouteWithChildren
  '/live': typeof LiveRoute
  '/manage': typeof ManageRouteWithChildren
  '/publish': typeof PublishRoute
  '/review': typeof ReviewRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/tools': typeof ToolsRouteWithChildren
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/external-uploads': typeof ApiExternalUploadsRouteWithChildren
  '/api/review': typeof ApiReviewRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/artifacts/$': typeof ArtifactsSplatRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/assets/$': typeof AssetsSplatRoute
  '/files/$id': typeof FilesIdRouteWithChildren
  '/health/$component': typeof HealthComponentRoute
  '/manage/documents': typeof ManageDocumentsRoute
  '/manage/status': typeof ManageStatusRoute
  '/tools/private': typeof ToolsPrivateRouteWithChildren
  '/manage/': typeof ManageIndexRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/external-uploads/$': typeof ApiExternalUploadsSplatRoute
  '/api/heartbeat/tower': typeof ApiHeartbeatTowerRoute
  '/api/ops/$': typeof ApiOpsSplatRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/review/$': typeof ApiReviewSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/files/$id/$': typeof FilesIdSplatRoute
  '/tools/private/money': typeof ToolsPrivateMoneyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/health'
    | '/live'
    | '/manage'
    | '/publish'
    | '/review'
    | '/sign-in'
    | '/status'
    | '/tools'
    | '/api/agent'
    | '/api/external-uploads'
    | '/api/review'
    | '/api/uploads'
    | '/artifacts/$'
    | '/artifacts/$id'
    | '/assets/$'
    | '/files/$id'
    | '/health/$component'
    | '/manage/documents'
    | '/manage/status'
    | '/tools/private'
    | '/manage/'
    | '/api/agent/$'
    | '/api/auth/$'
    | '/api/external-uploads/$'
    | '/api/heartbeat/tower'
    | '/api/ops/$'
    | '/api/public/catalog'
    | '/api/review/$'
    | '/api/uploads/$'
    | '/files/$id/$'
    | '/tools/private/money'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/health'
    | '/live'
    | '/publish'
    | '/review'
    | '/sign-in'
    | '/status'
    | '/tools'
    | '/api/agent'
    | '/api/external-uploads'
    | '/api/review'
    | '/api/uploads'
    | '/artifacts/$'
    | '/artifacts/$id'
    | '/assets/$'
    | '/files/$id'
    | '/health/$component'
    | '/manage/documents'
    | '/manage/status'
    | '/tools/private'
    | '/manage'
    | '/api/agent/$'
    | '/api/auth/$'
    | '/api/external-uploads/$'
    | '/api/heartbeat/tower'
    | '/api/ops/$'
    | '/api/public/catalog'
    | '/api/review/$'
    | '/api/uploads/$'
    | '/files/$id/$'
    | '/tools/private/money'
  id:
    | '__root__'
    | '/'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/health'
    | '/live'
    | '/manage'
    | '/publish'
    | '/review'
    | '/sign-in'
    | '/status'
    | '/tools'
    | '/api/agent'
    | '/api/external-uploads'
    | '/api/review'
    | '/api/uploads'
    | '/artifacts/$'
    | '/artifacts/$id'
    | '/assets/$'
    | '/files/$id'
    | '/health/$component'
    | '/manage/documents'
    | '/manage/status'
    | '/tools/private'
    | '/manage/'
    | '/api/agent/$'
    | '/api/auth/$'
    | '/api/external-uploads/$'
    | '/api/heartbeat/tower'
    | '/api/ops/$'
    | '/api/public/catalog'
    | '/api/review/$'
    | '/api/uploads/$'
    | '/files/$id/$'
    | '/tools/private/money'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  FaviconDotsvgRoute: typeof FaviconDotsvgRoute
  HealthRoute: typeof HealthRouteWithChildren
  LiveRoute: typeof LiveRoute
  ManageRoute: typeof ManageRouteWithChildren
  PublishRoute: typeof PublishRoute
  ReviewRoute: typeof ReviewRoute
  SignInRoute: typeof SignInRoute
  StatusRoute: typeof StatusRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  ApiExternalUploadsRoute: typeof ApiExternalUploadsRouteWithChildren
  ApiReviewRoute: typeof ApiReviewRouteWithChildren
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ArtifactsSplatRoute: typeof ArtifactsSplatRoute
  ArtifactsIdRoute: typeof ArtifactsIdRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  FilesIdRoute: typeof FilesIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiHeartbeatTowerRoute: typeof ApiHeartbeatTowerRoute
  ApiOpsSplatRoute: typeof ApiOpsSplatRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.svg': {
      id: '/favicon.svg'
      path: '/favicon.svg'
      fullPath: '/favicon.svg'
      preLoaderRoute: typeof FaviconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manage': {
      id: '/manage'
      path: '/manage'
      fullPath: '/manage'
      preLoaderRoute: typeof ManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-uploads': {
      id: '/api/external-uploads'
      path: '/api/external-uploads'
      fullPath: '/api/external-uploads'
      preLoaderRoute: typeof ApiExternalUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$': {
      id: '/artifacts/$'
      path: '/artifacts/$'
      fullPath: '/artifacts/$'
      preLoaderRoute: typeof ArtifactsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$id': {
      id: '/artifacts/$id'
      path: '/artifacts/$id'
      fullPath: '/artifacts/$id'
      preLoaderRoute: typeof ArtifactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$id': {
      id: '/files/$id'
      path: '/files/$id'
      fullPath: '/files/$id'
      preLoaderRoute: typeof FilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$component': {
      id: '/health/$component'
      path: '/$component'
      fullPath: '/health/$component'
      preLoaderRoute: typeof HealthComponentRouteImport
      parentRoute: typeof HealthRoute
    }
    '/manage/': {
      id: '/manage/'
      path: '/'
      fullPath: '/manage/'
      preLoaderRoute: typeof ManageIndexRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/documents': {
      id: '/manage/documents'
      path: '/documents'
      fullPath: '/manage/documents'
      preLoaderRoute: typeof ManageDocumentsRouteImport
      parentRoute: typeof ManageRoute
    }
    '/manage/status': {
      id: '/manage/status'
      path: '/status'
      fullPath: '/manage/status'
      preLoaderRoute: typeof ManageStatusRouteImport
      parentRoute: typeof ManageRoute
    }
    '/tools/private': {
      id: '/tools/private'
      path: '/private'
      fullPath: '/tools/private'
      preLoaderRoute: typeof ToolsPrivateRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/api/agent/$': {
      id: '/api/agent/$'
      path: '/$'
      fullPath: '/api/agent/$'
      preLoaderRoute: typeof ApiAgentSplatRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-uploads/$': {
      id: '/api/external-uploads/$'
      path: '/$'
      fullPath: '/api/external-uploads/$'
      preLoaderRoute: typeof ApiExternalUploadsSplatRouteImport
      parentRoute: typeof ApiExternalUploadsRoute
    }
    '/api/heartbeat/tower': {
      id: '/api/heartbeat/tower'
      path: '/api/heartbeat/tower'
      fullPath: '/api/heartbeat/tower'
      preLoaderRoute: typeof ApiHeartbeatTowerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/$': {
      id: '/api/ops/$'
      path: '/api/ops/$'
      fullPath: '/api/ops/$'
      preLoaderRoute: typeof ApiOpsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/$': {
      id: '/api/review/$'
      path: '/$'
      fullPath: '/api/review/$'
      preLoaderRoute: typeof ApiReviewSplatRouteImport
      parentRoute: typeof ApiReviewRoute
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/files/$id/$': {
      id: '/files/$id/$'
      path: '/$'
      fullPath: '/files/$id/$'
      preLoaderRoute: typeof FilesIdSplatRouteImport
      parentRoute: typeof FilesIdRoute
    }
    '/tools/private/money': {
      id: '/tools/private/money'
      path: '/money'
      fullPath: '/tools/private/money'
      preLoaderRoute: typeof ToolsPrivateMoneyRouteImport
      parentRoute: typeof ToolsPrivateRoute
    }
  }
}

interface HealthRouteChildren {
  HealthComponentRoute: typeof HealthComponentRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthComponentRoute: HealthComponentRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

interface ManageRouteChildren {
  ManageDocumentsRoute: typeof ManageDocumentsRoute
  ManageStatusRoute: typeof ManageStatusRoute
  ManageIndexRoute: typeof ManageIndexRoute
}

const ManageRouteChildren: ManageRouteChildren = {
  ManageDocumentsRoute: ManageDocumentsRoute,
  ManageStatusRoute: ManageStatusRoute,
  ManageIndexRoute: ManageIndexRoute,
}

const ManageRouteWithChildren =
  ManageRoute._addFileChildren(ManageRouteChildren)

interface ToolsPrivateRouteChildren {
  ToolsPrivateMoneyRoute: typeof ToolsPrivateMoneyRoute
}

const ToolsPrivateRouteChildren: ToolsPrivateRouteChildren = {
  ToolsPrivateMoneyRoute: ToolsPrivateMoneyRoute,
}

const ToolsPrivateRouteWithChildren = ToolsPrivateRoute._addFileChildren(
  ToolsPrivateRouteChildren,
)

interface ToolsRouteChildren {
  ToolsPrivateRoute: typeof ToolsPrivateRouteWithChildren
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsPrivateRoute: ToolsPrivateRouteWithChildren,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

interface ApiAgentRouteChildren {
  ApiAgentSplatRoute: typeof ApiAgentSplatRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentSplatRoute: ApiAgentSplatRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

interface ApiExternalUploadsRouteChildren {
  ApiExternalUploadsSplatRoute: typeof ApiExternalUploadsSplatRoute
}

const ApiExternalUploadsRouteChildren: ApiExternalUploadsRouteChildren = {
  ApiExternalUploadsSplatRoute: ApiExternalUploadsSplatRoute,
}

const ApiExternalUploadsRouteWithChildren =
  ApiExternalUploadsRoute._addFileChildren(ApiExternalUploadsRouteChildren)

interface ApiReviewRouteChildren {
  ApiReviewSplatRoute: typeof ApiReviewSplatRoute
}

const ApiReviewRouteChildren: ApiReviewRouteChildren = {
  ApiReviewSplatRoute: ApiReviewSplatRoute,
}

const ApiReviewRouteWithChildren = ApiReviewRoute._addFileChildren(
  ApiReviewRouteChildren,
)

interface ApiUploadsRouteChildren {
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

interface FilesIdRouteChildren {
  FilesIdSplatRoute: typeof FilesIdSplatRoute
}

const FilesIdRouteChildren: FilesIdRouteChildren = {
  FilesIdSplatRoute: FilesIdSplatRoute,
}

const FilesIdRouteWithChildren =
  FilesIdRoute._addFileChildren(FilesIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  FaviconDotsvgRoute: FaviconDotsvgRoute,
  HealthRoute: HealthRouteWithChildren,
  LiveRoute: LiveRoute,
  ManageRoute: ManageRouteWithChildren,
  PublishRoute: PublishRoute,
  ReviewRoute: ReviewRoute,
  SignInRoute: SignInRoute,
  StatusRoute: StatusRoute,
  ToolsRoute: ToolsRouteWithChildren,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  ApiExternalUploadsRoute: ApiExternalUploadsRouteWithChildren,
  ApiReviewRoute: ApiReviewRouteWithChildren,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ArtifactsSplatRoute: ArtifactsSplatRoute,
  ArtifactsIdRoute: ArtifactsIdRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  FilesIdRoute: FilesIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiHeartbeatTowerRoute: ApiHeartbeatTowerRoute,
  ApiOpsSplatRoute: ApiOpsSplatRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
