/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FaviconDoticoRouteImport } from './routes/favicon[.]ico'
import { Route as FaviconDotsvgRouteImport } from './routes/favicon[.]svg'
import { Route as FieldGuideRouteImport } from './routes/field-guide'
import { Route as HealthRouteImport } from './routes/health'
import { Route as LiveRouteImport } from './routes/live'
import { Route as MoneyRouteImport } from './routes/money'
import { Route as PublisherRouteImport } from './routes/publisher'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as StatusRouteImport } from './routes/status'
import { Route as ApiAgentRouteImport } from './routes/api/agent'
import { Route as ApiExternalUploadsRouteImport } from './routes/api/external-uploads'
import { Route as ApiReviewRouteImport } from './routes/api/review'
import { Route as ApiUploadsRouteImport } from './routes/api/uploads'
import { Route as ArtifactsSplatRouteImport } from './routes/artifacts/$'
import { Route as ArtifactsIdRouteImport } from './routes/artifacts/$id'
import { Route as AssetsSplatRouteImport } from './routes/assets/$'
import { Route as FilesIdRouteImport } from './routes/files/$id'
import { Route as HealthComponentRouteImport } from './routes/health/$component'
import { Route as PublisherIndexRouteImport } from './routes/publisher/index'
import { Route as PublisherArtifactsRouteImport } from './routes/publisher/artifacts'
import { Route as ApiAgentSplatRouteImport } from './routes/api/agent/$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiExternalUploadsSplatRouteImport } from './routes/api/external-uploads/$'
import { Route as ApiMoneyActivityRouteImport } from './routes/api/money/activity'
import { Route as ApiMoneyBalancesRouteImport } from './routes/api/money/balances'
import { Route as ApiMoneyCategoriesRouteImport } from './routes/api/money/categories'
import { Route as ApiMoneyImportsRouteImport } from './routes/api/money/imports'
import { Route as ApiOpsSplatRouteImport } from './routes/api/ops/$'
import { Route as ApiPublicCatalogRouteImport } from './routes/api/public/catalog'
import { Route as ApiReviewSplatRouteImport } from './routes/api/review/$'
import { Route as ApiUploadsSplatRouteImport } from './routes/api/uploads/$'
import { Route as FilesIdSplatRouteImport } from './routes/files/$id/$'
import { Route as ApiMoneyImportsPreviewRouteImport } from './routes/api/money/imports/preview'
import { Route as ApiStatusHeartbeatsMonitorIdRouteImport } from './routes/api/status/heartbeats/$monitorId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDoticoRoute = FaviconDoticoRouteImport.update({
  id: '/favicon.ico',
  path: '/favicon.ico',
  getParentRoute: () => rootRouteImport,
} as any)
const FaviconDotsvgRoute = FaviconDotsvgRouteImport.update({
  id: '/favicon.svg',
  path: '/favicon.svg',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldGuideRoute = FieldGuideRouteImport.update({
  id: '/field-guide',
  path: '/field-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const MoneyRoute = MoneyRouteImport.update({
  id: '/money',
  path: '/money',
  getParentRoute: () => rootRouteImport,
} as any)
const PublisherRoute = PublisherRouteImport.update({
  id: '/publisher',
  path: '/publisher',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentRoute = ApiAgentRouteImport.update({
  id: '/api/agent',
  path: '/api/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalUploadsRoute = ApiExternalUploadsRouteImport.update({
  id: '/api/external-uploads',
  path: '/api/external-uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewRoute = ApiReviewRouteImport.update({
  id: '/api/review',
  path: '/api/review',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsRoute = ApiUploadsRouteImport.update({
  id: '/api/uploads',
  path: '/api/uploads',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsSplatRoute = ArtifactsSplatRouteImport.update({
  id: '/artifacts/$',
  path: '/artifacts/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtifactsIdRoute = ArtifactsIdRouteImport.update({
  id: '/artifacts/$id',
  path: '/artifacts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsSplatRoute = AssetsSplatRouteImport.update({
  id: '/assets/$',
  path: '/assets/$',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIdRoute = FilesIdRouteImport.update({
  id: '/files/$id',
  path: '/files/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthComponentRoute = HealthComponentRouteImport.update({
  id: '/$component',
  path: '/$component',
  getParentRoute: () => HealthRoute,
} as any)
const PublisherIndexRoute = PublisherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublisherRoute,
} as any)
const PublisherArtifactsRoute = PublisherArtifactsRouteImport.update({
  id: '/artifacts',
  path: '/artifacts',
  getParentRoute: () => PublisherRoute,
} as any)
const ApiAgentSplatRoute = ApiAgentSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiAgentRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExternalUploadsSplatRoute = ApiExternalUploadsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiExternalUploadsRoute,
} as any)
const ApiMoneyActivityRoute = ApiMoneyActivityRouteImport.update({
  id: '/api/money/activity',
  path: '/api/money/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoneyBalancesRoute = ApiMoneyBalancesRouteImport.update({
  id: '/api/money/balances',
  path: '/api/money/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoneyCategoriesRoute = ApiMoneyCategoriesRouteImport.update({
  id: '/api/money/categories',
  path: '/api/money/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoneyImportsRoute = ApiMoneyImportsRouteImport.update({
  id: '/api/money/imports',
  path: '/api/money/imports',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpsSplatRoute = ApiOpsSplatRouteImport.update({
  id: '/api/ops/$',
  path: '/api/ops/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatalogRoute = ApiPublicCatalogRouteImport.update({
  id: '/api/public/catalog',
  path: '/api/public/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReviewSplatRoute = ApiReviewSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiReviewRoute,
} as any)
const ApiUploadsSplatRoute = ApiUploadsSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => ApiUploadsRoute,
} as any)
const FilesIdSplatRoute = FilesIdSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => FilesIdRoute,
} as any)
const ApiMoneyImportsPreviewRoute = ApiMoneyImportsPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ApiMoneyImportsRoute,
} as any)
const ApiStatusHeartbeatsMonitorIdRoute =
  ApiStatusHeartbeatsMonitorIdRouteImport.update({
    id: '/api/status/heartbeats/$monitorId',
    path: '/api/status/heartbeats/$monitorId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/field-guide': typeof FieldGuideRoute
  '/health': typeof HealthRouteWithChildren
  '/live': typeof LiveRoute
  '/money': typeof MoneyRoute
  '/publisher': typeof PublisherRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/external-uploads': typeof ApiExternalUploadsRouteWithChildren
  '/api/review': typeof ApiReviewRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/artifacts/$': typeof ArtifactsSplatRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/assets/$': typeof AssetsSplatRoute
  '/files/$id': typeof FilesIdRouteWithChildren
  '/health/$component': typeof HealthComponentRoute
  '/publisher/artifacts': typeof PublisherArtifactsRoute
  '/publisher/': typeof PublisherIndexRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/external-uploads/$': typeof ApiExternalUploadsSplatRoute
  '/api/money/activity': typeof ApiMoneyActivityRoute
  '/api/money/balances': typeof ApiMoneyBalancesRoute
  '/api/money/categories': typeof ApiMoneyCategoriesRoute
  '/api/money/imports': typeof ApiMoneyImportsRouteWithChildren
  '/api/ops/$': typeof ApiOpsSplatRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/review/$': typeof ApiReviewSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/files/$id/$': typeof FilesIdSplatRoute
  '/api/money/imports/preview': typeof ApiMoneyImportsPreviewRoute
  '/api/status/heartbeats/$monitorId': typeof ApiStatusHeartbeatsMonitorIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/field-guide': typeof FieldGuideRoute
  '/health': typeof HealthRouteWithChildren
  '/live': typeof LiveRoute
  '/money': typeof MoneyRoute
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/external-uploads': typeof ApiExternalUploadsRouteWithChildren
  '/api/review': typeof ApiReviewRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/artifacts/$': typeof ArtifactsSplatRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/assets/$': typeof AssetsSplatRoute
  '/files/$id': typeof FilesIdRouteWithChildren
  '/health/$component': typeof HealthComponentRoute
  '/publisher/artifacts': typeof PublisherArtifactsRoute
  '/publisher': typeof PublisherIndexRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/external-uploads/$': typeof ApiExternalUploadsSplatRoute
  '/api/money/activity': typeof ApiMoneyActivityRoute
  '/api/money/balances': typeof ApiMoneyBalancesRoute
  '/api/money/categories': typeof ApiMoneyCategoriesRoute
  '/api/money/imports': typeof ApiMoneyImportsRouteWithChildren
  '/api/ops/$': typeof ApiOpsSplatRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/review/$': typeof ApiReviewSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/files/$id/$': typeof FilesIdSplatRoute
  '/api/money/imports/preview': typeof ApiMoneyImportsPreviewRoute
  '/api/status/heartbeats/$monitorId': typeof ApiStatusHeartbeatsMonitorIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/documents': typeof DocumentsRoute
  '/favicon.ico': typeof FaviconDoticoRoute
  '/favicon.svg': typeof FaviconDotsvgRoute
  '/field-guide': typeof FieldGuideRoute
  '/health': typeof HealthRouteWithChildren
  '/live': typeof LiveRoute
  '/money': typeof MoneyRoute
  '/publisher': typeof PublisherRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/status': typeof StatusRoute
  '/api/agent': typeof ApiAgentRouteWithChildren
  '/api/external-uploads': typeof ApiExternalUploadsRouteWithChildren
  '/api/review': typeof ApiReviewRouteWithChildren
  '/api/uploads': typeof ApiUploadsRouteWithChildren
  '/artifacts/$': typeof ArtifactsSplatRoute
  '/artifacts/$id': typeof ArtifactsIdRoute
  '/assets/$': typeof AssetsSplatRoute
  '/files/$id': typeof FilesIdRouteWithChildren
  '/health/$component': typeof HealthComponentRoute
  '/publisher/artifacts': typeof PublisherArtifactsRoute
  '/publisher/': typeof PublisherIndexRoute
  '/api/agent/$': typeof ApiAgentSplatRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/external-uploads/$': typeof ApiExternalUploadsSplatRoute
  '/api/money/activity': typeof ApiMoneyActivityRoute
  '/api/money/balances': typeof ApiMoneyBalancesRoute
  '/api/money/categories': typeof ApiMoneyCategoriesRoute
  '/api/money/imports': typeof ApiMoneyImportsRouteWithChildren
  '/api/ops/$': typeof ApiOpsSplatRoute
  '/api/public/catalog': typeof ApiPublicCatalogRoute
  '/api/review/$': typeof ApiReviewSplatRoute
  '/api/uploads/$': typeof ApiUploadsSplatRoute
  '/files/$id/$': typeof FilesIdSplatRoute
  '/api/money/imports/preview': typeof ApiMoneyImportsPreviewRoute
  '/api/status/heartbeats/$monitorId': typeof ApiStatusHeartbeatsMonitorIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/documents'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/field-guide'
    | '/health'
    | '/live'
    | '/money'
    | '/publisher'
    | '/sign-in'
    | '/status'
    | '/api/agent'
    | '/api/external-uploads'
    | '/api/review'
    | '/api/uploads'
    | '/artifacts/$'
    | '/artifacts/$id'
    | '/assets/$'
    | '/files/$id'
    | '/health/$component'
    | '/publisher/artifacts'
    | '/publisher/'
    | '/api/agent/$'
    | '/api/auth/$'
    | '/api/external-uploads/$'
    | '/api/money/activity'
    | '/api/money/balances'
    | '/api/money/categories'
    | '/api/money/imports'
    | '/api/ops/$'
    | '/api/public/catalog'
    | '/api/review/$'
    | '/api/uploads/$'
    | '/files/$id/$'
    | '/api/money/imports/preview'
    | '/api/status/heartbeats/$monitorId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/documents'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/field-guide'
    | '/health'
    | '/live'
    | '/money'
    | '/sign-in'
    | '/status'
    | '/api/agent'
    | '/api/external-uploads'
    | '/api/review'
    | '/api/uploads'
    | '/artifacts/$'
    | '/artifacts/$id'
    | '/assets/$'
    | '/files/$id'
    | '/health/$component'
    | '/publisher/artifacts'
    | '/publisher'
    | '/api/agent/$'
    | '/api/auth/$'
    | '/api/external-uploads/$'
    | '/api/money/activity'
    | '/api/money/balances'
    | '/api/money/categories'
    | '/api/money/imports'
    | '/api/ops/$'
    | '/api/public/catalog'
    | '/api/review/$'
    | '/api/uploads/$'
    | '/files/$id/$'
    | '/api/money/imports/preview'
    | '/api/status/heartbeats/$monitorId'
  id:
    | '__root__'
    | '/'
    | '/documents'
    | '/favicon.ico'
    | '/favicon.svg'
    | '/field-guide'
    | '/health'
    | '/live'
    | '/money'
    | '/publisher'
    | '/sign-in'
    | '/status'
    | '/api/agent'
    | '/api/external-uploads'
    | '/api/review'
    | '/api/uploads'
    | '/artifacts/$'
    | '/artifacts/$id'
    | '/assets/$'
    | '/files/$id'
    | '/health/$component'
    | '/publisher/artifacts'
    | '/publisher/'
    | '/api/agent/$'
    | '/api/auth/$'
    | '/api/external-uploads/$'
    | '/api/money/activity'
    | '/api/money/balances'
    | '/api/money/categories'
    | '/api/money/imports'
    | '/api/ops/$'
    | '/api/public/catalog'
    | '/api/review/$'
    | '/api/uploads/$'
    | '/files/$id/$'
    | '/api/money/imports/preview'
    | '/api/status/heartbeats/$monitorId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocumentsRoute: typeof DocumentsRoute
  FaviconDoticoRoute: typeof FaviconDoticoRoute
  FaviconDotsvgRoute: typeof FaviconDotsvgRoute
  FieldGuideRoute: typeof FieldGuideRoute
  HealthRoute: typeof HealthRouteWithChildren
  LiveRoute: typeof LiveRoute
  MoneyRoute: typeof MoneyRoute
  PublisherRoute: typeof PublisherRouteWithChildren
  SignInRoute: typeof SignInRoute
  StatusRoute: typeof StatusRoute
  ApiAgentRoute: typeof ApiAgentRouteWithChildren
  ApiExternalUploadsRoute: typeof ApiExternalUploadsRouteWithChildren
  ApiReviewRoute: typeof ApiReviewRouteWithChildren
  ApiUploadsRoute: typeof ApiUploadsRouteWithChildren
  ArtifactsSplatRoute: typeof ArtifactsSplatRoute
  ArtifactsIdRoute: typeof ArtifactsIdRoute
  AssetsSplatRoute: typeof AssetsSplatRoute
  FilesIdRoute: typeof FilesIdRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiMoneyActivityRoute: typeof ApiMoneyActivityRoute
  ApiMoneyBalancesRoute: typeof ApiMoneyBalancesRoute
  ApiMoneyCategoriesRoute: typeof ApiMoneyCategoriesRoute
  ApiMoneyImportsRoute: typeof ApiMoneyImportsRouteWithChildren
  ApiOpsSplatRoute: typeof ApiOpsSplatRoute
  ApiPublicCatalogRoute: typeof ApiPublicCatalogRoute
  ApiStatusHeartbeatsMonitorIdRoute: typeof ApiStatusHeartbeatsMonitorIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.ico': {
      id: '/favicon.ico'
      path: '/favicon.ico'
      fullPath: '/favicon.ico'
      preLoaderRoute: typeof FaviconDoticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favicon.svg': {
      id: '/favicon.svg'
      path: '/favicon.svg'
      fullPath: '/favicon.svg'
      preLoaderRoute: typeof FaviconDotsvgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-guide': {
      id: '/field-guide'
      path: '/field-guide'
      fullPath: '/field-guide'
      preLoaderRoute: typeof FieldGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/money': {
      id: '/money'
      path: '/money'
      fullPath: '/money'
      preLoaderRoute: typeof MoneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publisher': {
      id: '/publisher'
      path: '/publisher'
      fullPath: '/publisher'
      preLoaderRoute: typeof PublisherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent': {
      id: '/api/agent'
      path: '/api/agent'
      fullPath: '/api/agent'
      preLoaderRoute: typeof ApiAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-uploads': {
      id: '/api/external-uploads'
      path: '/api/external-uploads'
      fullPath: '/api/external-uploads'
      preLoaderRoute: typeof ApiExternalUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review': {
      id: '/api/review'
      path: '/api/review'
      fullPath: '/api/review'
      preLoaderRoute: typeof ApiReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads': {
      id: '/api/uploads'
      path: '/api/uploads'
      fullPath: '/api/uploads'
      preLoaderRoute: typeof ApiUploadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$': {
      id: '/artifacts/$'
      path: '/artifacts/$'
      fullPath: '/artifacts/$'
      preLoaderRoute: typeof ArtifactsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artifacts/$id': {
      id: '/artifacts/$id'
      path: '/artifacts/$id'
      fullPath: '/artifacts/$id'
      preLoaderRoute: typeof ArtifactsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets/$': {
      id: '/assets/$'
      path: '/assets/$'
      fullPath: '/assets/$'
      preLoaderRoute: typeof AssetsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$id': {
      id: '/files/$id'
      path: '/files/$id'
      fullPath: '/files/$id'
      preLoaderRoute: typeof FilesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/$component': {
      id: '/health/$component'
      path: '/$component'
      fullPath: '/health/$component'
      preLoaderRoute: typeof HealthComponentRouteImport
      parentRoute: typeof HealthRoute
    }
    '/publisher/': {
      id: '/publisher/'
      path: '/'
      fullPath: '/publisher/'
      preLoaderRoute: typeof PublisherIndexRouteImport
      parentRoute: typeof PublisherRoute
    }
    '/publisher/artifacts': {
      id: '/publisher/artifacts'
      path: '/artifacts'
      fullPath: '/publisher/artifacts'
      preLoaderRoute: typeof PublisherArtifactsRouteImport
      parentRoute: typeof PublisherRoute
    }
    '/api/agent/$': {
      id: '/api/agent/$'
      path: '/$'
      fullPath: '/api/agent/$'
      preLoaderRoute: typeof ApiAgentSplatRouteImport
      parentRoute: typeof ApiAgentRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/external-uploads/$': {
      id: '/api/external-uploads/$'
      path: '/$'
      fullPath: '/api/external-uploads/$'
      preLoaderRoute: typeof ApiExternalUploadsSplatRouteImport
      parentRoute: typeof ApiExternalUploadsRoute
    }
    '/api/money/activity': {
      id: '/api/money/activity'
      path: '/api/money/activity'
      fullPath: '/api/money/activity'
      preLoaderRoute: typeof ApiMoneyActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/money/balances': {
      id: '/api/money/balances'
      path: '/api/money/balances'
      fullPath: '/api/money/balances'
      preLoaderRoute: typeof ApiMoneyBalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/money/categories': {
      id: '/api/money/categories'
      path: '/api/money/categories'
      fullPath: '/api/money/categories'
      preLoaderRoute: typeof ApiMoneyCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/money/imports': {
      id: '/api/money/imports'
      path: '/api/money/imports'
      fullPath: '/api/money/imports'
      preLoaderRoute: typeof ApiMoneyImportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ops/$': {
      id: '/api/ops/$'
      path: '/api/ops/$'
      fullPath: '/api/ops/$'
      preLoaderRoute: typeof ApiOpsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog': {
      id: '/api/public/catalog'
      path: '/api/public/catalog'
      fullPath: '/api/public/catalog'
      preLoaderRoute: typeof ApiPublicCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/review/$': {
      id: '/api/review/$'
      path: '/$'
      fullPath: '/api/review/$'
      preLoaderRoute: typeof ApiReviewSplatRouteImport
      parentRoute: typeof ApiReviewRoute
    }
    '/api/uploads/$': {
      id: '/api/uploads/$'
      path: '/$'
      fullPath: '/api/uploads/$'
      preLoaderRoute: typeof ApiUploadsSplatRouteImport
      parentRoute: typeof ApiUploadsRoute
    }
    '/files/$id/$': {
      id: '/files/$id/$'
      path: '/$'
      fullPath: '/files/$id/$'
      preLoaderRoute: typeof FilesIdSplatRouteImport
      parentRoute: typeof FilesIdRoute
    }
    '/api/money/imports/preview': {
      id: '/api/money/imports/preview'
      path: '/preview'
      fullPath: '/api/money/imports/preview'
      preLoaderRoute: typeof ApiMoneyImportsPreviewRouteImport
      parentRoute: typeof ApiMoneyImportsRoute
    }
    '/api/status/heartbeats/$monitorId': {
      id: '/api/status/heartbeats/$monitorId'
      path: '/api/status/heartbeats/$monitorId'
      fullPath: '/api/status/heartbeats/$monitorId'
      preLoaderRoute: typeof ApiStatusHeartbeatsMonitorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HealthRouteChildren {
  HealthComponentRoute: typeof HealthComponentRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthComponentRoute: HealthComponentRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

interface PublisherRouteChildren {
  PublisherArtifactsRoute: typeof PublisherArtifactsRoute
  PublisherIndexRoute: typeof PublisherIndexRoute
}

const PublisherRouteChildren: PublisherRouteChildren = {
  PublisherArtifactsRoute: PublisherArtifactsRoute,
  PublisherIndexRoute: PublisherIndexRoute,
}

const PublisherRouteWithChildren = PublisherRoute._addFileChildren(
  PublisherRouteChildren,
)

interface ApiAgentRouteChildren {
  ApiAgentSplatRoute: typeof ApiAgentSplatRoute
}

const ApiAgentRouteChildren: ApiAgentRouteChildren = {
  ApiAgentSplatRoute: ApiAgentSplatRoute,
}

const ApiAgentRouteWithChildren = ApiAgentRoute._addFileChildren(
  ApiAgentRouteChildren,
)

interface ApiExternalUploadsRouteChildren {
  ApiExternalUploadsSplatRoute: typeof ApiExternalUploadsSplatRoute
}

const ApiExternalUploadsRouteChildren: ApiExternalUploadsRouteChildren = {
  ApiExternalUploadsSplatRoute: ApiExternalUploadsSplatRoute,
}

const ApiExternalUploadsRouteWithChildren =
  ApiExternalUploadsRoute._addFileChildren(ApiExternalUploadsRouteChildren)

interface ApiReviewRouteChildren {
  ApiReviewSplatRoute: typeof ApiReviewSplatRoute
}

const ApiReviewRouteChildren: ApiReviewRouteChildren = {
  ApiReviewSplatRoute: ApiReviewSplatRoute,
}

const ApiReviewRouteWithChildren = ApiReviewRoute._addFileChildren(
  ApiReviewRouteChildren,
)

interface ApiUploadsRouteChildren {
  ApiUploadsSplatRoute: typeof ApiUploadsSplatRoute
}

const ApiUploadsRouteChildren: ApiUploadsRouteChildren = {
  ApiUploadsSplatRoute: ApiUploadsSplatRoute,
}

const ApiUploadsRouteWithChildren = ApiUploadsRoute._addFileChildren(
  ApiUploadsRouteChildren,
)

interface FilesIdRouteChildren {
  FilesIdSplatRoute: typeof FilesIdSplatRoute
}

const FilesIdRouteChildren: FilesIdRouteChildren = {
  FilesIdSplatRoute: FilesIdSplatRoute,
}

const FilesIdRouteWithChildren =
  FilesIdRoute._addFileChildren(FilesIdRouteChildren)

interface ApiMoneyImportsRouteChildren {
  ApiMoneyImportsPreviewRoute: typeof ApiMoneyImportsPreviewRoute
}

const ApiMoneyImportsRouteChildren: ApiMoneyImportsRouteChildren = {
  ApiMoneyImportsPreviewRoute: ApiMoneyImportsPreviewRoute,
}

const ApiMoneyImportsRouteWithChildren = ApiMoneyImportsRoute._addFileChildren(
  ApiMoneyImportsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocumentsRoute: DocumentsRoute,
  FaviconDoticoRoute: FaviconDoticoRoute,
  FaviconDotsvgRoute: FaviconDotsvgRoute,
  FieldGuideRoute: FieldGuideRoute,
  HealthRoute: HealthRouteWithChildren,
  LiveRoute: LiveRoute,
  MoneyRoute: MoneyRoute,
  PublisherRoute: PublisherRouteWithChildren,
  SignInRoute: SignInRoute,
  StatusRoute: StatusRoute,
  ApiAgentRoute: ApiAgentRouteWithChildren,
  ApiExternalUploadsRoute: ApiExternalUploadsRouteWithChildren,
  ApiReviewRoute: ApiReviewRouteWithChildren,
  ApiUploadsRoute: ApiUploadsRouteWithChildren,
  ArtifactsSplatRoute: ArtifactsSplatRoute,
  ArtifactsIdRoute: ArtifactsIdRoute,
  AssetsSplatRoute: AssetsSplatRoute,
  FilesIdRoute: FilesIdRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiMoneyActivityRoute: ApiMoneyActivityRoute,
  ApiMoneyBalancesRoute: ApiMoneyBalancesRoute,
  ApiMoneyCategoriesRoute: ApiMoneyCategoriesRoute,
  ApiMoneyImportsRoute: ApiMoneyImportsRouteWithChildren,
  ApiOpsSplatRoute: ApiOpsSplatRoute,
  ApiPublicCatalogRoute: ApiPublicCatalogRoute,
  ApiStatusHeartbeatsMonitorIdRoute: ApiStatusHeartbeatsMonitorIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
