import { bigint, boolean, index, integer, jsonb, pgSchema, primaryKey, text, timestamp, uuid } from "drizzle-orm/pg-core";

export const toolsSchema = pgSchema("tools");
export const artifactsSchema = pgSchema("artifacts");
export const checkRuns = toolsSchema.table("check_runs", { id: text("id").primaryKey(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), completedAt: timestamp("completed_at", { withTimezone: true }) });
export const observations = toolsSchema.table("observations", { id: uuid("id").primaryKey(), runId: text("run_id").notNull().references(() => checkRuns.id), monitorId: text("monitor_id").notNull(), checkedAt: timestamp("checked_at", { withTimezone: true }).notNull(), success: boolean("success").notNull(), statusCode: integer("status_code"), latencyMs: integer("latency_ms").notNull(), errorCode: text("error_code") }, (table) => [index("observations_monitor_checked_idx").on(table.monitorId, table.checkedAt)]);
export const incidents = toolsSchema.table("incidents", { id: uuid("id").primaryKey(), monitorId: text("monitor_id").notNull(), startedAt: timestamp("started_at", { withTimezone: true }).notNull(), resolvedAt: timestamp("resolved_at", { withTimezone: true }), openingObservationId: uuid("opening_observation_id"), closingObservationId: uuid("closing_observation_id") }, (table) => [index("incidents_monitor_started_idx").on(table.monitorId, table.startedAt)]);
export const heartbeats = toolsSchema.table("heartbeats", { monitorId: text("monitor_id").primaryKey(), lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull() });
export const monitorOverrides = toolsSchema.table("monitor_overrides", { monitorId: text("monitor_id").primaryKey(), paused: boolean("paused").notNull().default(false), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull() });
export const scheduledTaskRuns = toolsSchema.table("scheduled_task_runs", { taskId: text("task_id").notNull(), slot: timestamp("slot", { withTimezone: true }).notNull(), ownerId: text("owner_id").notNull(), leaseUntil: timestamp("lease_until", { withTimezone: true }).notNull(), completedAt: timestamp("completed_at", { withTimezone: true }), result: jsonb("result").$type<Record<string, unknown>>() }, (table) => [primaryKey({ columns: [table.taskId, table.slot] })]);
export const artifactMetadata = artifactsSchema.table("objects", { id: text("id").primaryKey(), kind: text("kind").notNull(), filename: text("filename").notNull(), contentType: text("content_type").notNull(), bytes: bigint("bytes", { mode: "number" }).notNull(), objectKey: text("object_key").notNull().unique(), project: text("project"), createdAt: timestamp("created_at", { withTimezone: true }).notNull(), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull(), expiresAt: timestamp("expires_at", { withTimezone: true }), revokedAt: timestamp("revoked_at", { withTimezone: true }) });
