import { useCallback,useEffect,useState } from "react";
import type { ApiError,HistoryResponse,MonitorListResponse,MonitorSummary } from "../shared/contracts";

async function api<T>(path:string,options?:RequestInit):Promise<T>{const response=await fetch(path,options);const value:unknown=response.status===204?null:await response.json();if(!response.ok){const error=value as ApiError;throw new Error(error.error?.message??"Request failed");}return value as T;}
function fmt(value:string|null):string{if(!value)return "Never";const date=new Date(value);return Number.isNaN(date.valueOf())?"Never":new Intl.RelativeTimeFormat(undefined,{numeric:"auto"}).format(Math.round((date.valueOf()-Date.now())/60000),"minute");}
function uptime(value:number|null):string{return value===null?"—":`${value.toFixed(2)}%`;}
function Status({monitor}:{monitor:MonitorSummary}){return <span className={`status status-${monitor.status}`}><span aria-hidden="true" />{monitor.status}</span>;}
function Sparkline({history}:{history:HistoryResponse}){const values=history.buckets.filter((p)=>p.latencyMs!==null);if(values.length<2)return <p className="muted">Not enough data for a latency graph.</p>;const max=Math.max(...values.map((v)=>v.latencyMs??0),1);const points=values.map((v,index)=>`${index/(values.length-1)*300},${62-(v.latencyMs??0)/max*56}`).join(" ");return <svg className="spark" viewBox="0 0 300 68" role="img" aria-label="Recent latency"><polyline points={points}/></svg>;}

export function App(){
  const [data,setData]=useState<MonitorListResponse|null>(null);const [selected,setSelected]=useState<number|null>(null);const [history,setHistory]=useState<HistoryResponse|null>(null);const [window,setWindow]=useState<"24h"|"30d">("24h");const [adding,setAdding]=useState(false);const [editing,setEditing]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState<string|null>(null);
  const load=useCallback(async()=>{try{setError(null);setData(await api<MonitorListResponse>("/api/monitors"));}catch(reason){setError(reason instanceof Error?reason.message:"Could not load monitors");}},[]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(selected===null){setHistory(null);return;}void api<HistoryResponse>(`/api/monitors/${selected}/history?window=${window}`).then(setHistory).catch((reason:unknown)=>setError(reason instanceof Error?reason.message:"Could not load history"));},[selected,window,data]);
  const mutate=async(action:()=>Promise<unknown>):Promise<true>=>{setBusy(true);setError(null);try{await action();await load();return true;}catch(reason){setError(reason instanceof Error?reason.message:"Action failed");throw reason;}finally{setBusy(false);}};
  const monitor=data?.monitors.find((item)=>item.id===selected)??null;
  if(!data&&!error)return <main><header><div className="eyebrow">Private status</div><h1>Uptime</h1></header><div className="skeleton" aria-label="Loading monitors"/><div className="skeleton short"/></main>;
  return <main>
    <header><div><div className="eyebrow">Private status</div><h1>Uptime</h1><p className="lede">Your sites, checked every five minutes.</p></div><button onClick={()=>setAdding(true)}>Add monitor</button></header>
    {error&&<div className="error" role="alert">{error}<button className="text-button" onClick={()=>void load()}>Retry</button></div>}
    <section className="summary" aria-label="Overview"><div><strong>{data?.capacity.used??0}/40</strong><span>monitor capacity</span></div><div><strong>{data?.monitors.filter((m)=>m.status==="up").length??0}</strong><span>currently up</span></div><div><strong>{data?.discordConfigured?"Ready":"Not set"}</strong><span>Discord webhook</span></div></section>
    <section className="toolbar"><h2>Monitors</h2>{data?.discordConfigured&&<button className="secondary" disabled={busy} onClick={()=>void mutate(()=>api("/api/notifications/discord/test",{method:"POST"})).catch(()=>undefined)}>Send Discord test</button>}</section>
    {!data?.discordConfigured&&<p className="notice">Discord notifications are not configured. Add the <code>DISCORD_WEBHOOK_URL</code> Worker secret to enable alerts.</p>}
    {data?.monitors.length===0?<section className="empty"><h2>No monitors yet</h2><p>Add your first HTTP or HTTPS site. Its first check starts immediately.</p><button onClick={()=>setAdding(true)}>Add a monitor</button></section>:
      <div className="monitor-list">{data?.monitors.map((item)=><button className="monitor-row" key={item.id} onClick={()=>setSelected(item.id)} aria-label={`Open ${item.name}, status ${item.status}`}><div><strong>{item.name}</strong><span>{item.hostname}</span></div><Status monitor={item}/><div><strong>{item.latestLatencyMs===null?"—":`${item.latestLatencyMs} ms`}</strong><span>latency</span></div><div><strong>{uptime(item.uptime24h)}</strong><span>24h uptime</span></div><div><strong>{fmt(item.lastCheckedAt)}</strong><span>last checked</span></div><span aria-hidden="true">›</span></button>)}</div>}
    {adding&&<div className="modal" role="dialog" aria-modal="true" aria-labelledby="add-title"><form onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);void mutate(()=>api("/api/monitors",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(form.get("name")),url:String(form.get("url"))})})).then(()=>setAdding(false)).catch(()=>undefined);}}><h2 id="add-title">Add monitor</h2><label>Name<input name="name" maxLength={80} required autoFocus /></label><label>Website URL<input name="url" type="url" placeholder="https://example.com" required /></label><div className="actions"><button type="button" className="secondary" onClick={()=>setAdding(false)}>Cancel</button><button disabled={busy}>Add and check</button></div></form></div>}
    {editing&&monitor&&<div className="modal" role="dialog" aria-modal="true" aria-labelledby="edit-title"><form onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);void mutate(()=>api(`/api/monitors/${monitor.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:String(form.get("name")),url:String(form.get("url"))})})).then(()=>setEditing(false)).catch(()=>undefined);}}><h2 id="edit-title">Edit monitor</h2><label>Name<input name="name" defaultValue={monitor.name} maxLength={80} required autoFocus /></label><label>Website URL<input name="url" type="url" defaultValue={monitor.url} required /></label><p className="muted">Changing the URL resets its current state to checking while keeping its history and schedule slot.</p><div className="actions"><button type="button" className="secondary" onClick={()=>setEditing(false)}>Cancel</button><button disabled={busy}>Save changes</button></div></form></div>}
    {monitor&&<div className="drawer" role="dialog" aria-modal="true" aria-labelledby="detail-title"><div className="drawer-head"><div><Status monitor={monitor}/><h2 id="detail-title">{monitor.name}</h2><a href={monitor.url} target="_blank" rel="noreferrer">{monitor.hostname}</a></div><button className="icon" aria-label="Close details" onClick={()=>setSelected(null)}>×</button></div><div className="detail-stats"><div><strong>{uptime(history?.uptime??null)}</strong><span>{window} uptime</span></div><div><strong>{monitor.latestLatencyMs===null?"—":`${monitor.latestLatencyMs} ms`}</strong><span>latest latency</span></div></div><div className="tabs"><button className={window==="24h"?"active":""} onClick={()=>setWindow("24h")}>24 hours</button><button className={window==="30d"?"active":""} onClick={()=>setWindow("30d")}>30 days</button></div>{history?<><Sparkline history={history}/><h3>Recent checks</h3><div className="checks">{history.checks.slice(0,12).map((check)=><div key={check.id}><span className={check.success?"dot good":"dot bad"}/><span>{check.success?`${check.statusCode} OK`:check.errorCode?.replaceAll("_"," ")}</span><span>{check.latencyMs} ms</span><time>{fmt(check.checkedAt)}</time></div>)}</div><h3>Incidents</h3>{history.incidents.length?<div className="incidents">{history.incidents.map((incident)=><div key={incident.id}><strong>{incident.resolvedAt?"Resolved":"Ongoing"}</strong><span>Started {fmt(incident.startedAt)} · Discord: {incident.downDeliveredAt?(incident.resolvedAt?(incident.recoveryDeliveredAt?"recovery sent":"recovery pending"):"down alert sent"):"alert pending"}</span></div>)}</div>:<p className="muted">No incidents in this window.</p>}</>:<div className="skeleton"/>}<div className="drawer-actions"><button disabled={busy||!monitor.enabled} onClick={()=>void mutate(()=>api(`/api/monitors/${monitor.id}/check`,{method:"POST"})).catch(()=>undefined)}>Recheck now</button><button className="secondary" disabled={busy} onClick={()=>setEditing(true)}>Edit</button><button className="secondary" disabled={busy} onClick={()=>void mutate(()=>api(`/api/monitors/${monitor.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({enabled:!monitor.enabled})})).catch(()=>undefined)}>{monitor.enabled?"Pause":"Resume"}</button><button className="danger" disabled={busy} onClick={()=>{if(globalThis.confirm(`Delete ${monitor.name} and all its history?`))void mutate(()=>api(`/api/monitors/${monitor.id}`,{method:"DELETE"})).then(()=>setSelected(null)).catch(()=>undefined);}}>Delete</button></div></div>}
  </main>;
}
