import crypto from "node:crypto";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "bun:test";
import { openSQLite } from "../src/db/sqlite.js";
import { SQLiteReviewRepository } from "../src/sqlite-repository.js";

const directories:string[]=[];
afterEach(()=>{for(const directory of directories.splice(0))rmSync(directory,{recursive:true,force:true});});
function setup(){const directory=mkdtempSync(join(tmpdir(),"field-guide-sqlite-"));directories.push(directory);const handle=openSQLite(join(directory,"review.sqlite"));return {handle,repository:new SQLiteReviewRepository(handle.client,handle.close)};}
function candidate(id=crypto.randomUUID()){return {candidateId:id,scope:"project" as const,projectKey:"unicode",projectDisplayName:"Nested 🚂",lessonKey:"sqlite",title:"SQLite ✅",body:"Store nested JSON",rationale:"Lower idle cost",evidence:[{excerpt:"nested",sessionRef:"会議",commitHashes:["abc", "déf"]}],createdAt:"2026-07-26T00:00:00.123Z"};}

describe("SQLite repository",()=>{
  it("preserves idempotency, nested Unicode JSON, timestamps, cursors, and receipt constraints",async()=>{const {handle,repository}=setup();const value=candidate();expect(await repository.createCandidate("key",value)).toBe("created");expect(await repository.createCandidate("key",value)).toBe("replay");await expect(repository.createCandidate("key",{...value,title:"different"})).rejects.toThrow("different content");const decision=await repository.decide(value.candidateId,1,{action:"approve"},new Date(value.createdAt),"owner@example.com");expect(decision.reviewedAt).toBe(value.createdAt);expect((await repository.decisions(undefined,10)).decisions[0]?.evidence).toEqual(value.evidence);expect(await repository.createReceipt("receipt",decision.decisionId,"2026-07-26T00:01:00.456Z","applied")).toBe("created");expect(await repository.createReceipt("receipt",decision.decisionId,"2026-07-26T00:01:00.456Z","applied")).toBe("replay");expect(handle.client.query("PRAGMA foreign_key_check").all()).toEqual([]);await repository.close();});
  it("enforces foreign keys and a single amendment per parent",async()=>{const {handle,repository}=setup();expect(()=>handle.client.run("INSERT INTO application_receipts VALUES(?,?,?,?,?)",["bad","hash",crypto.randomUUID(),"2026-07-26T00:00:00.000Z","applied"])).toThrow();const value=candidate();await repository.createCandidate("key",value);const original=await repository.decide(value.candidateId,1,{action:"approve"},new Date(value.createdAt),"owner@example.com");const amendment=await repository.amendDecision(value.candidateId,1,{expectedDecisionId:original.decisionId,action:"reject"},new Date("2026-07-26T01:00:00Z"),"owner@example.com");await expect(repository.amendDecision(value.candidateId,1,{expectedDecisionId:original.decisionId,action:"approve"},new Date("2026-07-26T02:00:00Z"),"owner@example.com")).rejects.toThrow("Decision changed");expect(()=>handle.client.run("INSERT INTO verdict_events(decision_id,candidate_id,round,action,reviewer,reviewed_at,round_kind,effect,amends_decision_id) VALUES(?,?,?,?,?,?,?,?,?)",[crypto.randomUUID(),value.candidateId,1,"approve","owner","2026-07-26T03:00:00.000Z","initial","activate",original.decisionId])).toThrow();expect(amendment.amendsDecisionId).toBe(original.decisionId);await repository.close();});
  it("serializes competing verdicts without a partial write and advances sequence",async()=>{const {handle,repository}=setup();const value=candidate();await repository.createCandidate("key",value);const results=await Promise.allSettled([repository.decide(value.candidateId,1,{action:"approve"},new Date(value.createdAt),"a@example.com"),repository.decide(value.candidateId,1,{action:"reject"},new Date(value.createdAt),"b@example.com")]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(results.filter(r=>r.status==="rejected")).toHaveLength(1);expect(handle.client.query<{count:number},[]>("SELECT COUNT(*) count FROM verdict_events").get()?.count).toBe(1);const next=handle.client.query<{sequence:number},[]>("SELECT sequence FROM verdict_events").get()?.sequence;expect(next).toBe(1);await repository.close();});
});
