"use client";

import { useMemo, useRef, useState } from "react";
import { useRouter } from "@tanstack/react-router";
import { Check, FileSpreadsheet, Search, Upload } from "lucide-react";
import type { MoneyTrackerPageData } from "../src/protected-data.js";
import { MONEY_CATEGORIES, MONEY_TRANSFER_DISPOSITIONS, type MoneyCategory, type MoneyImportPreview, type MoneyTransferDisposition } from "./money-import-domain.js";
import type { MoneyActivityPage, MoneyImportReceipt } from "./money-repository.js";
import { Alert, AlertDescription, AlertTitle } from "../src/components/ui/alert.js";
import { Badge } from "../src/components/ui/badge.js";
import { Button } from "../src/components/ui/button.js";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../src/components/ui/card.js";
import { Input } from "../src/components/ui/input.js";

type Activity = MoneyTrackerPageData["activity"][number];

export function MoneyActivityView({ activity, transactionCount, transferReview }: Pick<MoneyTrackerPageData, "activity" | "transactionCount" | "transferReview">) {
  const router = useRouter();
  const [rows, setRows] = useState(activity);
  const [query, setQuery] = useState("");
  const [flow, setFlow] = useState<"all" | Activity["flowKind"]>("all");
  const [reviewOnly, setReviewOnly] = useState(false);
  const [saving, setSaving] = useState<string>();
  const [loading, setLoading] = useState(false);
  const [hasMore, setHasMore] = useState(activity.length < transactionCount);
  const [error, setError] = useState<string>();
  const [ruleCandidate, setRuleCandidate] = useState<Activity>();
  const [ruleAffected, setRuleAffected] = useState<number>();
  const visible = useMemo(() => {
    const normalized = query.trim().toLocaleLowerCase("en-GB");
    return rows.filter((item) => (!reviewOnly || item.needsTransferReview) && (flow === "all" || item.flowKind === flow) && (!normalized || `${item.description} ${item.accountName} ${item.sourceType}`.toLocaleLowerCase("en-GB").includes(normalized)));
  }, [rows, flow, query, reviewOnly]);
  const categorize = async (item: Activity, category: MoneyCategory, createRule = false) => {
    setSaving(item.id); setError(undefined);
    try {
      const result = await moneyJson<{ ok: true; affectedCount: number }>("/api/money/categories", { transactionId: item.id, category, createRule });
      setRows((current) => current.map((row) => row.id === item.id ? { ...row, category, categoryOrigin: "manual" } : row));
      setRuleCandidate(createRule ? undefined : { ...item, category, categoryOrigin: "manual" });
      setRuleAffected(createRule ? result.affectedCount : undefined);
      await router.invalidate();
      if (createRule && result.affectedCount > 1) await searchAll();
    } catch (caught) { setError(message(caught)); } finally { setSaving(undefined); }
  };
  const loadActivity = async (review: boolean, append = false) => {
    setLoading(true); setError(undefined);
    try {
      const offset = append ? rows.length : 0;
      const parameters = new URLSearchParams({ query, offset: String(offset), limit: "500" });
      if (flow !== "all") parameters.set("flow", flow);
      if (review) parameters.set("review", "true");
      const page = await moneyGet<MoneyActivityPage>(`/api/money/activity?${parameters}`);
      setRows((current) => append ? [...current, ...page.items] : [...page.items]);
      setHasMore(page.hasMore);
    } catch (caught) { setError(message(caught)); } finally { setLoading(false); }
  };
  const searchAll = (append = false) => loadActivity(reviewOnly, append);
  const toggleReview = async () => { const next = !reviewOnly; setReviewOnly(next); await loadActivity(next); };
  const setDisposition = async (item: Activity, disposition: MoneyTransferDisposition) => {
    setSaving(item.id); setError(undefined);
    try {
      await moneyJson("/api/money/transfers", { transactionId: item.id, disposition });
      setRows((current) => current.map((row) => row.id === item.id ? { ...row, transferDisposition: disposition, needsTransferReview: false } : row));
      if (reviewOnly) await loadActivity(true);
      await router.invalidate();
    } catch (caught) { setError(message(caught)); } finally { setSaving(undefined); }
  };
  return <>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Activity summary">
      <LedgerMetric label="Imported transactions" value={transactionCount.toLocaleString("en-GB")} detail={`${activity.length} newest loaded`} />
      <LedgerMetric label="Needs review" value={(transferReview.unresolvedPositiveCount + transferReview.unresolvedNegativeCount).toLocaleString("en-GB")} detail={`${transferReview.unresolvedPositiveCount} inflows · ${transferReview.unresolvedNegativeCount} outflows`} />
      <LedgerMetric label="Reverted" value={activity.filter((item) => item.status === "reverted").length.toLocaleString("en-GB")} detail="excluded from analytics" />
      <LedgerMetric label="Linked transfers" value={transferReview.linkedPairs.toLocaleString("en-GB")} detail={`${transferReview.unlinkedCount.toLocaleString("en-GB")} remain unlinked`} />
    </section>
    {transferReview.unresolvedPositiveCount + transferReview.unresolvedNegativeCount > 0 || reviewOnly ? <Button className="w-fit" type="button" variant="outline" disabled={loading} onClick={() => void toggleReview()}>{reviewOnly ? "Show all activity" : "Show transfer review rows"}</Button> : null}
    {visible.some((item) => item.flowKind === "transfer" && !item.transferGroupId) ? <Card><CardHeader className="border-b"><CardTitle>Transfer treatment</CardTitle><CardDescription>Choose the accounting meaning independently from its category.</CardDescription></CardHeader><CardContent className="divide-y p-0">{visible.filter((item) => item.flowKind === "transfer" && !item.transferGroupId).map((item) => <div className="grid items-center gap-3 px-4 py-3 text-sm sm:grid-cols-[minmax(0,1fr)_9rem_12rem]" key={item.id}><span className="truncate">{item.description || item.sourceType}</span><span className="text-right font-mono">{signedMoney(item.amountMinor, item.currency)}</span><select aria-label={`Transfer treatment for ${item.description}`} className="h-8 rounded-md border border-input bg-background px-2 text-xs" disabled={saving === item.id} value={item.transferDisposition ?? ""} onChange={(event) => void setDisposition(item, event.currentTarget.value as MoneyTransferDisposition)}><option value="" disabled>Needs review</option>{MONEY_TRANSFER_DISPOSITIONS.map((disposition) => <option key={disposition} value={disposition}>{flowLabel(disposition)}</option>)}</select></div>)}</CardContent></Card> : null}
    {error ? <Alert variant="destructive"><AlertTitle>Category not saved</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : null}
    {ruleCandidate ? <Alert><AlertTitle>Saved for this row</AlertTitle><AlertDescription><span>Apply this exact description to other transactions in {ruleCandidate.accountName}?</span><Button className="ml-3" type="button" size="sm" variant="outline" disabled={saving === ruleCandidate.id} onClick={() => void categorize(ruleCandidate, ruleCandidate.category, true)}>Create account rule</Button></AlertDescription></Alert> : null}
    {ruleAffected !== undefined ? <Alert><AlertTitle>Account rule applied</AlertTitle><AlertDescription>{ruleAffected.toLocaleString("en-GB")} transaction{ruleAffected === 1 ? "" : "s"} now use this category.</AlertDescription></Alert> : null}
    <Card>
      <CardHeader className="border-b"><div className="flex flex-wrap items-end justify-between gap-3"><div><CardTitle>Transaction activity</CardTitle><CardDescription>Category changes affect one row. Reusable rules are explicit and account-scoped.</CardDescription></div><div className="flex w-full flex-wrap gap-2 sm:w-auto"><label className="relative min-w-52 flex-1 sm:flex-none"><Search className="pointer-events-none absolute left-2.5 top-2.5 size-4 text-muted-foreground" /><span className="sr-only">Search activity</span><Input className="pl-8" type="search" value={query} onChange={(event) => { setQuery(event.currentTarget.value); setHasMore(false); }} placeholder="Search activity" /></label><select className="h-9 rounded-md border border-input bg-background px-2.5 text-sm" value={flow} onChange={(event) => { setFlow(event.currentTarget.value as typeof flow); setHasMore(false); }} aria-label="Filter by flow kind"><option value="all">All flows</option>{["spend", "refund", "transfer", "trade", "investment_income", "fee", "tax", "income", "balance_adjustment"].map((value) => <option key={value} value={value}>{flowLabel(value)}</option>)}</select><Button type="button" variant="outline" disabled={loading} onClick={() => void searchAll()}>{loading ? "Loading…" : "Search all"}</Button></div></div></CardHeader>
      <CardContent className="overflow-x-auto p-0">{visible.length ? <><table className="w-full min-w-[68rem] text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="px-4 py-3 text-left">Date</th><th className="px-4 py-3 text-left">Description</th><th className="px-4 py-3 text-left">Account</th><th className="px-4 py-3 text-left">Flow</th><th className="px-4 py-3 text-left">Category</th><th className="px-4 py-3 text-right">Costs</th><th className="px-4 py-3 text-right">Amount</th><th className="px-4 py-3 text-right">Status</th></tr></thead><tbody className="divide-y">{visible.map((item) => <tr key={item.id} className="hover:bg-muted/30"><td className="whitespace-nowrap px-4 py-3 text-muted-foreground">{formatDate(item.occurredAt)}</td><td className="max-w-80 px-4 py-3"><p className="truncate font-medium" title={item.description}>{item.description || item.sourceType}</p><p className="text-xs text-muted-foreground">{item.sourceType}{item.transferGroupId ? " · linked transfer" : ""}</p></td><td className="whitespace-nowrap px-4 py-3">{item.accountName}</td><td className="px-4 py-3"><Badge variant="outline">{flowLabel(item.flowKind)}</Badge></td><td className="px-4 py-3"><select className={`h-8 rounded-md border border-input bg-background px-2 text-xs ${item.category === "uncategorized" ? "text-amber-300" : ""}`} value={item.category} disabled={saving === item.id} onChange={(event) => void categorize(item, event.currentTarget.value as MoneyCategory)} aria-label={`Category for ${item.description}`}>{MONEY_CATEGORIES.map((category) => <option key={category} value={category}>{category}</option>)}</select><span className="ml-2 text-[.65rem] text-muted-foreground">{item.categoryOrigin}</span></td><td className="px-4 py-3 text-right font-mono text-muted-foreground">{item.feeMinor + item.taxMinor ? money(item.feeMinor + item.taxMinor, item.currency) : "—"}</td><td className={`px-4 py-3 text-right font-mono font-medium ${item.amountMinor < 0 ? "text-rose-300" : "text-emerald-300"}`}>{signedMoney(item.amountMinor, item.currency)}</td><td className="px-4 py-3 text-right"><Badge variant={item.status === "completed" ? "outline" : "destructive"}>{item.status}</Badge></td></tr>)}</tbody></table>{hasMore ? <div className="border-t p-3 text-center"><Button type="button" variant="outline" disabled={loading} onClick={() => void searchAll(true)}>{loading ? "Loading…" : "Load more"}</Button></div> : null}</> : <EmptyLedger title={rows.length ? "No matching activity" : "No transactions imported"} description={rows.length ? "Run Search all to query the full ledger." : "Import a supported statement from Imports."} />}</CardContent>
    </Card>
  </>;
}

export function MoneyImportsView({ imports }: Pick<MoneyTrackerPageData, "imports">) {
  const router = useRouter(); const input = useRef<HTMLInputElement>(null);
  const [file, setFile] = useState<File>(); const [preview, setPreview] = useState<MoneyImportPreview>(); const [receipt, setReceipt] = useState<MoneyImportReceipt>();
  const [busy, setBusy] = useState<"preview" | "commit">(); const [error, setError] = useState<string>();
  const choose = (selected?: File) => { setFile(selected); setPreview(undefined); setReceipt(undefined); setError(undefined); };
  const previewFile = async () => { if (!file) return; setBusy("preview"); setError(undefined); try { const form = new FormData(); form.set("file", file); setPreview(await moneyForm<MoneyImportPreview>("/api/money/imports/preview", form)); } catch (caught) { setError(message(caught)); } finally { setBusy(undefined); } };
  const commit = async () => { if (!file || !preview) return; setBusy("commit"); setError(undefined); try { const form = new FormData(); form.set("file", file); form.set("expectedDigest", preview.digest); const result = await moneyForm<MoneyImportReceipt>("/api/money/imports", form); setReceipt(result); setPreview(undefined); setFile(undefined); if (input.current) input.current.value = ""; await router.invalidate(); } catch (caught) { setError(message(caught)); } finally { setBusy(undefined); } };
  return <section className="grid items-start gap-3 lg:grid-cols-[minmax(0,1.25fr)_minmax(20rem,.75fr)]"><Card><CardHeader className="border-b"><CardTitle>Import a statement</CardTitle><CardDescription>Revolut cash/trading TSV, portfolio CSV, or balance CSV with Date, Account, Value, Role, Currency</CardDescription></CardHeader><CardContent className="space-y-4 pt-5"><input ref={input} className="sr-only" type="file" accept=".tsv,.csv,text/tab-separated-values,text/csv" onChange={(event) => choose(event.currentTarget.files?.[0])} /><button type="button" className="grid min-h-44 w-full place-items-center rounded-lg border border-dashed bg-muted/25 p-6 text-center transition-colors hover:bg-muted/40" onClick={() => input.current?.click()}><span><FileSpreadsheet className="mx-auto mb-3 size-8 text-cyan-300" /><strong className="block">{file?.name ?? "Choose a money export"}</strong><span className="mt-1 block text-sm text-muted-foreground">{file ? formatBytes(file.size) : "TSV or CSV, up to 10 MB"}</span></span></button>{error ? <Alert variant="destructive"><AlertTitle>Import unavailable</AlertTitle><AlertDescription>{error}</AlertDescription></Alert> : null}{receipt ? <Alert><Check /><AlertTitle>{receipt.replay ? "Already imported" : "Import complete"}</AlertTitle><AlertDescription>{receipt.insertedCount.toLocaleString("en-GB")} rows inserted and {receipt.duplicateCount.toLocaleString("en-GB")} duplicates skipped.</AlertDescription></Alert> : null}{!preview ? <Button type="button" disabled={!file || busy !== undefined} onClick={() => void previewFile()}><Upload />{busy === "preview" ? "Reading statement…" : "Preview import"}</Button> : <PreviewPanel preview={preview} onCancel={() => setPreview(undefined)} onCommit={() => void commit()} busy={busy === "commit"} />}</CardContent></Card><Card><CardHeader className="border-b"><CardTitle>Import history</CardTitle><CardDescription>Raw files are discarded after normalization</CardDescription></CardHeader><CardContent className="divide-y p-0">{imports.length ? imports.map((item) => <div className="space-y-1 px-4 py-3" key={item.id}><div className="flex items-start justify-between gap-3"><strong className="min-w-0 truncate text-sm" title={item.filename}>{item.filename}</strong><Badge variant="outline">{item.insertedCount.toLocaleString("en-GB")} new</Badge></div><p className="text-xs text-muted-foreground">{formatDate(item.committedAt)} · {formatBytes(item.bytes)} · {item.duplicateCount.toLocaleString("en-GB")} duplicates</p><p className="text-[.65rem] uppercase tracking-wide text-muted-foreground">{formatLabel(item.format)}</p></div>) : <EmptyLedger title="No imports yet" description="Completed imports will appear here with their row counts and digest-backed receipt." />}</CardContent></Card></section>;
}

export function MoneySpendingView({ spending }: Pick<MoneyTrackerPageData, "spending">) {
  const recent = spending.months.slice(-12); const totals = recent.reduce((sum, month) => ({ spend: sum.spend + month.spendMinor, refunds: sum.refunds + month.refundsMinor, income: sum.income + month.incomeMinor, net: sum.net + month.netCashFlowMinor }), { spend: 0, refunds: 0, income: 0, net: 0 });
  const maximum = Math.max(...recent.map((month) => month.spendMinor), 1);
  return <><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><LedgerMetric label="12m spending" value={money(totals.spend, "EUR")} /><LedgerMetric label="12m income" value={money(totals.income, "EUR")} /><LedgerMetric label="12m net cash flow" value={signedMoney(totals.net, "EUR")} /><LedgerMetric label="Needs category" value={spending.uncategorizedCount.toLocaleString("en-GB")} detail="all history" /></section><section className="grid items-start gap-3 lg:grid-cols-[minmax(0,1.35fr)_minmax(18rem,.65fr)]"><Card><CardHeader className="border-b"><CardTitle>Monthly spending</CardTitle><CardDescription>Completed EUR spend, excluding transfers, trades, adjustments, and reverted rows</CardDescription></CardHeader><CardContent className="space-y-2 pt-5">{recent.length ? recent.map((month) => <div className="grid grid-cols-[4.5rem_minmax(4rem,1fr)_7rem] items-center gap-3 text-xs" key={month.month}><span className="text-muted-foreground">{month.month}</span><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-cyan-300" style={{ width: `${month.spendMinor / maximum * 100}%` }} /></div><span className="text-right font-mono">{money(month.spendMinor, "EUR")}</span></div>) : <EmptyLedger title="No spending history" description="Import a cash or card statement to build full-history analytics." />}</CardContent></Card><Card><CardHeader className="border-b"><CardTitle>Categories</CardTitle><CardDescription>All completed EUR spending</CardDescription></CardHeader><CardContent className="divide-y p-0">{spending.categories.length ? spending.categories.map((item) => <div className="flex items-center justify-between gap-3 px-4 py-3 text-sm" key={item.category}><span>{item.category}<span className="ml-2 text-xs text-muted-foreground">{item.count}</span></span><strong className="font-mono font-medium">{money(item.amountMinor, "EUR")}</strong></div>) : <EmptyLedger title="No category totals" description="Category totals appear after importing completed spending." />}</CardContent></Card></section></>;
}

export function MoneyInvestmentsView({ investments }: Pick<MoneyTrackerPageData, "investments">) {
  const { totals, positions } = investments;
  return <><Alert><AlertTitle>Cash-flow view, not portfolio valuation</AlertTitle><AlertDescription>Quantities, contributions, sales, income, fees, and taxes come from imported events. No live prices or investment returns are inferred.</AlertDescription></Alert><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><LedgerMetric label="Investment events" value={totals.eventCount.toLocaleString("en-GB")} /><LedgerMetric label="Bought" value={money(totals.boughtMinor, "EUR")} /><LedgerMetric label="Sold" value={money(totals.soldMinor, "EUR")} /><LedgerMetric label="Income" value={money(totals.incomeMinor, "EUR")} /><LedgerMetric label="Fees + taxes" value={money(totals.feesMinor + totals.taxesMinor, "EUR")} /></section><Card><CardHeader className="border-b"><CardTitle>Imported positions</CardTitle><CardDescription>Net source quantities and cumulative EUR cash flows by symbol</CardDescription></CardHeader><CardContent className="overflow-x-auto p-0">{positions.length ? <table className="w-full min-w-[52rem] text-sm"><thead className="border-b text-xs text-muted-foreground"><tr><th className="px-4 py-3 text-left">Asset</th><th className="px-4 py-3 text-left">Class</th><th className="px-4 py-3 text-right">Quantity</th><th className="px-4 py-3 text-right">Bought</th><th className="px-4 py-3 text-right">Sold</th><th className="px-4 py-3 text-right">Income</th><th className="px-4 py-3 text-right">Costs</th></tr></thead><tbody className="divide-y">{positions.map((item, index) => <tr key={`${item.symbol}:${item.name ?? index}`}><td className="px-4 py-3"><strong>{item.symbol}</strong>{item.name ? <span className="ml-2 text-xs text-muted-foreground">{item.name}</span> : null}</td><td className="px-4 py-3 text-muted-foreground">{item.assetClass ?? "—"}</td><td className="px-4 py-3 text-right font-mono">{item.quantity}</td><td className="px-4 py-3 text-right font-mono">{money(item.boughtMinor, item.currency)}</td><td className="px-4 py-3 text-right font-mono">{money(item.soldMinor, item.currency)}</td><td className="px-4 py-3 text-right font-mono text-emerald-300">{money(item.incomeMinor, item.currency)}</td><td className="px-4 py-3 text-right font-mono text-rose-300">{money(item.feesMinor + item.taxesMinor, item.currency)}</td></tr>)}</tbody></table> : <EmptyLedger title="No investment events" description="Import a supported trading TSV or portfolio CSV." />}</CardContent></Card></>;
}

export function MoneyPlanningCard({ planning }: Pick<MoneyTrackerPageData, "planning">) {
  return <Card><CardHeader className="border-b"><CardTitle>Planning baseline</CardTitle><CardDescription>Median of up to 12 complete calendar months. The current partial month is excluded.</CardDescription></CardHeader><CardContent className="pt-5">{planning.ready ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div><p className="text-xs text-muted-foreground">Monthly baseline</p><strong className="mt-1 block font-mono text-xl">{signedMoney(planning.medianMonthlyNetMinor, "EUR")}</strong><p className="mt-1 text-xs text-muted-foreground">{planning.observedMonthCount} complete months</p></div>{planning.projections.map((item) => <div className="rounded-md border bg-muted/20 p-3" key={item.months}><p className="text-xs text-muted-foreground">{item.months} month change</p><strong className={`mt-1 block font-mono text-lg ${item.changeMinor < 0 ? "text-rose-300" : "text-emerald-300"}`}>{signedMoney(item.changeMinor, "EUR")}</strong></div>)}</div> : <Alert><AlertTitle>Planning needs transfer review</AlertTitle><AlertDescription>{planning.unresolvedTransferCount.toLocaleString("en-GB")} unlinked transfer-like inflows or outflows still need classification. Projections stay hidden until review is complete.</AlertDescription></Alert>}</CardContent></Card>;
}

export function MoneyBalanceEntry() {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState<string>(); const [saved, setSaved] = useState(false);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); const element = event.currentTarget; setBusy(true); setError(undefined); setSaved(false); const form = new FormData(element); try { await moneyJson("/api/money/balances", { accountName: String(form.get("accountName") ?? ""), role: String(form.get("role") ?? ""), date: String(form.get("date") ?? ""), value: String(form.get("value") ?? ""), currency: "EUR" }); setSaved(true); element.reset(); await router.invalidate(); } catch (caught) { setError(message(caught)); } finally { setBusy(false); } };
  return <Card><CardHeader className="border-b"><CardTitle>Add balance snapshot</CardTitle><CardDescription>Manual EUR values are stored alongside imported running balances</CardDescription></CardHeader><CardContent className="pt-5"><form className="grid gap-3 sm:grid-cols-[minmax(10rem,1fr)_9rem_10rem_10rem_auto]" onSubmit={(event) => void submit(event)}><label className="space-y-1 text-xs text-muted-foreground">Account<Input name="accountName" required maxLength={100} placeholder="Broker or account" /></label><label className="space-y-1 text-xs text-muted-foreground">Role<select name="role" className="block h-9 w-full rounded-md border border-input bg-background px-2.5 text-sm text-foreground"><option value="cash">Cash</option><option value="investment">Investment</option></select></label><label className="space-y-1 text-xs text-muted-foreground">Date<Input name="date" type="date" required /></label><label className="space-y-1 text-xs text-muted-foreground">Value<Input name="value" inputMode="decimal" required placeholder="0.00" /></label><Button className="self-end" disabled={busy}>{busy ? "Saving…" : "Save snapshot"}</Button></form>{error ? <p className="mt-3 text-sm text-rose-300">{error}</p> : null}{saved ? <p className="mt-3 text-sm text-emerald-300">Snapshot saved.</p> : null}</CardContent></Card>;
}

function PreviewPanel({ preview, onCancel, onCommit, busy }: { preview: MoneyImportPreview; onCancel: () => void; onCommit: () => void; busy: boolean }) { return <div className="space-y-4 rounded-lg border bg-muted/20 p-4"><div><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="font-semibold">Ready to import</h3><Badge variant="outline">{preview.rowCount.toLocaleString("en-GB")} rows</Badge></div><p className="mt-1 text-xs text-muted-foreground">{formatLabel(preview.format)} · {preview.dateRange.from} to {preview.dateRange.to} · {preview.duplicateCount.toLocaleString("en-GB")} duplicates{preview.investmentEventCount ? ` · ${preview.investmentEventCount.toLocaleString("en-GB")} investment events` : ""}</p></div><div className="grid gap-2 sm:grid-cols-2">{preview.accounts.map((account) => <div className="rounded-md border bg-background p-3" key={account.externalRef}><div className="flex justify-between gap-3"><strong className="text-sm">{account.name}</strong><span className="font-mono text-sm">{account.endingBalanceMinor === undefined ? "—" : money(account.endingBalanceMinor, account.currency)}</span></div><p className="mt-1 text-xs text-muted-foreground">{account.rowCount.toLocaleString("en-GB")} rows · {account.revertedCount} reverted · {account.reconciliationMismatchCount ? `${account.reconciliationMismatchCount} mismatches` : "reconciled"}</p></div>)}</div>{preview.warnings.map((warning) => <Alert key={warning}><AlertTitle>Review warning</AlertTitle><AlertDescription>{warning}</AlertDescription></Alert>)}<div className="flex flex-wrap gap-2"><Button type="button" onClick={onCommit} disabled={busy}>{busy ? "Importing…" : `Import ${Math.max(0, preview.rowCount - preview.duplicateCount).toLocaleString("en-GB")} new rows`}</Button><Button type="button" variant="outline" onClick={onCancel} disabled={busy}>Cancel</Button></div><p className="text-xs text-muted-foreground">Commit reparses and digest-checks the file. Raw bytes are never retained.</p></div>; }
function LedgerMetric({ label, value, detail }: { label: string; value: string; detail?: string }) { return <Card><CardContent className="p-4"><p className="text-[.68rem] font-semibold uppercase tracking-[.08em] text-muted-foreground">{label}</p><strong className="mt-1.5 block text-2xl tracking-tight">{value}</strong>{detail ? <span className="mt-1 block text-xs text-muted-foreground">{detail}</span> : null}</CardContent></Card>; }
function EmptyLedger({ title, description }: { title: string; description: string }) { return <div className="grid min-h-36 place-items-center p-5 text-center"><div><p className="font-medium">{title}</p><p className="mx-auto mt-1 max-w-lg text-sm text-muted-foreground">{description}</p></div></div>; }
async function moneyForm<Result>(url: string, form: FormData): Promise<Result> { return moneyFetch<Result>(url, { body: form }); }
async function moneyJson<Result = { ok: true }>(url: string, value: Record<string, unknown>): Promise<Result> { return moneyFetch<Result>(url, { body: JSON.stringify(value), headers: { "Content-Type": "application/json" } }); }
async function moneyFetch<Result>(url: string, init: Pick<RequestInit, "body" | "headers">): Promise<Result> { const response = await fetch(url, { method: "POST", ...init }); const body = await response.json() as { message?: unknown } | Result; if (!response.ok) throw new Error(typeof (body as { message?: unknown }).message === "string" ? (body as { message: string }).message : `Money request failed with status ${response.status}.`); return body as Result; }
async function moneyGet<Result>(url: string): Promise<Result> { const response = await fetch(url); const body = await response.json() as { message?: unknown } | Result; if (!response.ok) throw new Error(typeof (body as { message?: unknown }).message === "string" ? (body as { message: string }).message : `Money request failed with status ${response.status}.`); return body as Result; }
function message(error: unknown) { return error instanceof Error ? error.message : "The money request failed."; }
function money(minor: number, currency: string) { return new Intl.NumberFormat("de-DE", { style: "currency", currency }).format(minor / 100); }
function signedMoney(minor: number, currency: string) { return `${minor >= 0 ? "+" : ""}${money(minor, currency)}`; }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeZone: "Europe/Berlin" }).format(new Date(value)); }
function formatBytes(bytes: number) { return bytes < 1024 ? `${bytes} B` : bytes < 1024 * 1024 ? `${(bytes / 1024).toFixed(1)} KB` : `${(bytes / 1024 / 1024).toFixed(1)} MB`; }
function flowLabel(flow: string) { return flow.replaceAll("_", " "); }
function formatLabel(value: string) { return value.replace(/_v\d$/, "").replaceAll("_", " "); }
